#User Preferences for Burke Porter CCRT
#Thu Dec 20 21:25:58 GMT-02:00 2007
server.address.failsafe=172.16.250.3
controlline.drivermonitor.model=DisplayDriverMonitor
server.address=192.168.1.1
controlline.starttest.model=StartTest
settings.reportprinter.name=hp LaserJet 1320 PCL 6
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
preference.country.iso=BR
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\DCBR.TestReport.xml
preference.language.iso=pt
controlline.testresults.model=TestResultToPrint
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\DCBR.TestReport.xml
settings.printer.localize=true
settings.ticketprinter.printonpass=false
preference.units=Metric
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
settings.graphicsprinter.enabled=false
controlline.licensewarning.model=InvalidLicenseNotification
settings.reportprinter.printonpass=true
network.ftppassword=porter
network.useproxy=false
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
server.use.stored.address=true
settings.reportprinter.printonfail=true
