#SecurityGuard configuration for password
#Mon Feb 06 16:16:07 EST 2006
config.role.user=Users have semi-restricted access to application configuration.
login.admin=nqzva
config.role.admin=Access to user administration and other restricted functions.
roles.test=user
login.test=grfg
auth.timeout=300
roles.admin=user admin
