#User Preferences for Burke Porter CCRT
#Wed Oct 26 10:30:08 GMT-02:00 2011
server.address.failsafe=192.168.1.1
controlline.drivermonitor.model=DisplayDriverMonitor
server.address=192.168.1.1
settings.ticketprinter.name.right=hp LaserJet 1320 PCL 6
controlline.starttest.model=StartTest
settings.reportprinter.name=hp LaserJet 1320 PCL 6
settings.ticketprinter.name=hp LaserJet 1320 PCL 6
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=BR
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ticketlayout.xml
preference.language.iso=pt
controlline.testresults.model=TestResultToPrint
settings.reportprinter.name.right=hp LaserJet 1320 PCL 6
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Dcx.ReportLayout.xml
settings.ticketprinter.printonpass=false
settings.printer.localize=true
preference.units=Metric
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
settings.graphicsprinter.enabled=false
controlline.licensewarning.model=InvalidLicenseNotification
settings.reportprinter.printonpass=true
network.ftppassword=porter
network.useproxy=false
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
server.use.stored.address=true
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Dcx.DCBR.ReportLayout.xsl
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\resultxform.xsl
settings.reportprinter.printonfail=true
