#User Preferences for Burke Porter CCRT
#Tue Jun 10 15:47:12 EDT 2008
server.address.failsafe=172.16.253.101
controlline.drivermonitor.model=DisplayDriverMonitor
settings.clicktoexit.value=false
server.address=172.16.253.101
controlline.starttest.model=StartTest
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=US
controlline.testinprogress.model=TestInProgress
preference.language.iso=en
controlline.testresults.model=TestResultToPrint
preference.units=English
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
controlline.licensewarning.model=InvalidLicenseNotification
network.ftppassword=porter
network.useproxy=false
controlline.rackmonitor.model=DisplayRackMonitor
email.smtp.host=localhost
network.ftproot=/home/ftp
server.use.stored.address=true
