#User Preferences for Burke Porter CCRT
#Tue Nov 05 14:06:39 GMT 2013
controlline.licensefatal.model=InvalidLicenseFatalFault
preference.logging=CONFIG
settings.ticketprinter.printonpass=false
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ReportLayout.xsl
controlline.starttest.model=StartTest
controlline.licensewarning.model=InvalidLicenseNotification
preference.units=English
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\reportlayout.xml
network.useproxy=true
network.ftppassword=porter
server.address.failsafe=192.168.1.2
settings.reportprinter.name=HP Officejet Pro K5400 Series
settings.ticketprinter.printonfail=true
controlline.rackmonitor.model=DisplayRackMonitor
settings.printer.localize=true
controlline.drivermonitor.model=DisplayDriverMonitor
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ReportLayout.xsl
server.address=192.168.1.3
preference.country.iso=US
email.smtp.host=localhost
network.ftproot=/home/ftp
settings.ticketprinter.name.right=HP Officejet Pro K5400 Series
preference.language.iso=en
email.from=CCRT System <ccrt@bepco.com>
network.ftpuser=burke
settings.reportprinter.printonpass=false
settings.reportprinter.name.right=HP Officejet Pro K5400 Series
controlline.testinprogress.model=TestInProgress
server.use.stored.address=true
settings.graphicsprinter.enabled=false
settings.clicktoexit.value=false
controlline.testresults.model=TestResultToPrint
settings.ticketprinter.name=HP Officejet Pro K5400 Series
settings.reportprinter.printonfail=true
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ticketlayout.xml
controlline.softwareid.model=SoftwareID
