backup.all.script=ntbackup backup "@C:\\Burke_PorterCCRT\\ccrt.bks" /L:f /j "CCRT full backup job" /F "C:\\backups\\ccrt.bkf"
backup.configuration.script=ntbackup backup "@C:\\Burke_PorterCCRT\\configuration.bks" /L:f /j "CCRT configuration backup job" /F "C:\\backups\\configuration.bkf"

