# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 9545 $

last_build_date=2008-07-17
core_build_today=1
cust_build_today=1
NAMETAG=Ccrt-C08071701
