//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyotaParameterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToyotaParameterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BepLogo {
            get {
                object obj = ResourceManager.GetObject("BepLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:\\Rewrite\\Configuration\\VehicleTest\\Toyota.Braketest.SelectionTable.xml.
        /// </summary>
        internal static string BrakeTestSelectionTable {
            get {
                return ResourceManager.GetString("BrakeTestSelectionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Burke_PorterCCRT\\resources\\com\\bepco\\rtc\\images\\.
        /// </summary>
        internal static string CcrtClientLogoFileLocation {
            get {
                return ResourceManager.GetString("CcrtClientLogoFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Burke_PorterCCRT\\resources\\com\\bepco\\rtc\\properties\\CRTPanelLabels.constants.
        /// </summary>
        internal static string CcrtClientLogoSelectFile {
            get {
                return ResourceManager.GetString("CcrtClientLogoSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Configuration/VehicleTest/DriveCurves/4wdAbsBrakeTestDriveCurve.xml.
        /// </summary>
        internal static string FourWheelDriveAbsTestSequence {
            get {
                return ResourceManager.GetString("FourWheelDriveAbsTestSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Configuration/VehicleTest/DriveCurves/4wdBrakeTestDriveCurve.xml.
        /// </summary>
        internal static string FourWheelDriveTestSequence {
            get {
                return ResourceManager.GetString("FourWheelDriveTestSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:\\Rewrite\\Configuration\\Servers\\Toyota.InputServerConfig.xml.
        /// </summary>
        internal static string InputServerFileName {
            get {
                return ResourceManager.GetString("InputServerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewVehicleTemplate.xml.
        /// </summary>
        internal static string NewVehicleTemplateFileName {
            get {
                return ResourceManager.GetString("NewVehicleTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterTranslationTable.xml.
        /// </summary>
        internal static string ParameterDisplayNameFile {
            get {
                return ResourceManager.GetString("ParameterDisplayNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:\\Rewrite\\Configuration\\VehicleTest\\BuildRecords\\.
        /// </summary>
        internal static string ParameterFilePath {
            get {
                return ResourceManager.GetString("ParameterFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemovedVehicleArchive.
        /// </summary>
        internal static string RemoveVehicleArchiveDirectory {
            get {
                return ResourceManager.GetString("RemoveVehicleArchiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Configuration/VehicleTest/DriveCurves/RollTestDriveCurve.xml.
        /// </summary>
        internal static string RollTestDriveCurve {
            get {
                return ResourceManager.GetString("RollTestDriveCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:\\Rewrite\\Configuration\\VehicleTest\\Toyota.Rolltest.SelectionTable.xml.
        /// </summary>
        internal static string RollTestSelectionTable {
            get {
                return ResourceManager.GetString("RollTestSelectionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:\\Rewrite\\Configuration\\VehicleTest\\.
        /// </summary>
        internal static string SelectionTableLocation {
            get {
                return ResourceManager.GetString("SelectionTableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Configuration/VehicleTest/DriveCurves/2wdAbsBrakeTestDriveCurve.xml.
        /// </summary>
        internal static string TwoWheelDriveAbsTestSequence {
            get {
                return ResourceManager.GetString("TwoWheelDriveAbsTestSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Configuration/VehicleTest/DriveCurves/2wdBrakeTestDriveCurve.xml.
        /// </summary>
        internal static string TwoWheelDriveTestSequence {
            get {
                return ResourceManager.GetString("TwoWheelDriveTestSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string VehicleLogoFileLocation {
            get {
                return ResourceManager.GetString("VehicleLogoFileLocation", resourceCulture);
            }
        }
    }
}
