# This file is for RemoteFileBrowsing
# $Revision$

browser.button.refresh = Refresh
browser.button.tooltip = Refresh the listing from the remote server
browser.progressbar.scan = Scanning Files...
browser.progressbar.populate = Populating Combo Box...

browser.io.error.title = Input / Output Error
browser.remotefile.error.title = Remote File Error