# Properties for the Backup restoring utility
filterdescription=Backup archive file 
title=Backup Restore Utility
menubar.file=File
menubar.menuitem.exit=Exit
frame.title=Backup Restore utility
buttontext.restore=Restore
configerror.badurl=Bad URL
configerror.nofileproxy=No file proxy found
configerror.badresource=Bad resource
server.ip=172.16.7.93
backup.directory=Backups
restore.script=on -d -t /dev/con9 -uroot /usr/local/bin/RestoreCCRT.sh

