# Localization for ServerLogChooserPanel

dialog.title.text = Server Log Chooser

label.progress.text = Scanning for log files...
label.error.text = Error:
button.retry.text = Retry
button.refresh.text = Refresh

missingchooser.error.title = No File Server
missingchooser.error.text = Could not access the file server to scan logs.

# Configure the desired on-server log file directories
#
# Each of these entries, eg, logdir.name.main, MUST HAVE A CORRESPONDING
# ENTRY in ServerLogChooserPanel.constants!!! (with the logdir.name.main key)
#
logdir.name.main = Main

logdir.name.vtests = VehicleTests

logdir.name.servers = Servers

logdir.name.comp = Components

logdir.name.comm = Communication

