# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 10764 $

last_build_date=2012-11-28
core_build_today=6
cust_build_today=1
NAMETAG=Ccrt-C12112806
