//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputServerLanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputServerLanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InputServer.InputServerLanguageResource", typeof(InputServerLanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate:.
        /// </summary>
        internal static string BaudRateLabel {
            get {
                return ResourceManager.GetString("BaudRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ConfigureMenu {
            get {
                return ResourceManager.GetString("ConfigureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database.
        /// </summary>
        internal static string ConnectDatabase {
            get {
                return ResourceManager.GetString("ConnectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to QNX CCRT system.
        /// </summary>
        internal static string ConnectToQnx {
            get {
                return ResourceManager.GetString("ConnectToQnx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count not find CCRT Database.
        /// </summary>
        internal static string CouldNotFindDatabase {
            get {
                return ResourceManager.GetString("CouldNotFindDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Log File.
        /// </summary>
        internal static string CurrentLogMenuItem {
            get {
                return ResourceManager.GetString("CurrentLogMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string DatabaseMenuItem {
            get {
                return ResourceManager.GetString("DatabaseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bits:.
        /// </summary>
        internal static string DataBitsLabel {
            get {
                return ResourceManager.GetString("DataBitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Item.
        /// </summary>
        internal static string DataItemColumn {
            get {
                return ResourceManager.GetString("DataItemColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Items.
        /// </summary>
        internal static string DataItemsMenuItem {
            get {
                return ResourceManager.GetString("DataItemsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Item Form.
        /// </summary>
        internal static string DataItemTitle {
            get {
                return ResourceManager.GetString("DataItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Settings:.
        /// </summary>
        internal static string DataSettingsLabel {
            get {
                return ResourceManager.GetString("DataSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Location.
        /// </summary>
        internal static string DbLocationMenuItem {
            get {
                return ResourceManager.GetString("DbLocationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Device Configuration.
        /// </summary>
        internal static string DeviceConfigTitle {
            get {
                return ResourceManager.GetString("DeviceConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DeviceNameColumn {
            get {
                return ResourceManager.GetString("DeviceNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string DeviceTypeColumn {
            get {
                return ResourceManager.GetString("DeviceTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Language.
        /// </summary>
        internal static string DisplayLanguageMenuItem {
            get {
                return ResourceManager.GetString("DisplayLanguageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishOption {
            get {
                return ResourceManager.GetString("EnglishOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting InputServer.
        /// </summary>
        internal static string ExitInputServer {
            get {
                return ResourceManager.GetString("ExitInputServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenuItem {
            get {
                return ResourceManager.GetString("ExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Data:.
        /// </summary>
        internal static string HeaderDataLabel {
            get {
                return ResourceManager.GetString("HeaderDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Length:.
        /// </summary>
        internal static string HeaderLengthLabel {
            get {
                return ResourceManager.GetString("HeaderLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Data.
        /// </summary>
        internal static string InputDataColumn {
            get {
                return ResourceManager.GetString("InputDataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Devices:.
        /// </summary>
        internal static string InputDevicesLabel {
            get {
                return ResourceManager.GetString("InputDevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Server.
        /// </summary>
        internal static string InputServerWindowTitle {
            get {
                return ResourceManager.GetString("InputServerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivalid IPAddress Format!.
        /// </summary>
        internal static string InvalidIpFormat {
            get {
                return ResourceManager.GetString("InvalidIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string LocalizationTitle {
            get {
                return ResourceManager.GetString("LocalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Directory.
        /// </summary>
        internal static string LogDirMenuItem {
            get {
                return ResourceManager.GetString("LogDirMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Messages:.
        /// </summary>
        internal static string LogMessagesLabel {
            get {
                return ResourceManager.GetString("LogMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length:.
        /// </summary>
        internal static string MaxLengthLabel {
            get {
                return ResourceManager.GetString("MaxLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Log File Count.
        /// </summary>
        internal static string MaxLogFileCountTitle {
            get {
                return ResourceManager.GetString("MaxLogFileCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Log Files.
        /// </summary>
        internal static string MaxLogFilesMenuItem {
            get {
                return ResourceManager.GetString("MaxLogFilesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Log Files:.
        /// </summary>
        internal static string MaxNumberOfFiles {
            get {
                return ResourceManager.GetString("MaxNumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length:.
        /// </summary>
        internal static string MinLengthLabel {
            get {
                return ResourceManager.GetString("MinLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor For Data:.
        /// </summary>
        internal static string MonitorDataLabel {
            get {
                return ResourceManager.GetString("MonitorDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database File Located!.
        /// </summary>
        internal static string NoDatabaseFile {
            get {
                return ResourceManager.GetString("NoDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening input devices.
        /// </summary>
        internal static string OpenInputDevices {
            get {
                return ResourceManager.GetString("OpenInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening log file.
        /// </summary>
        internal static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity:.
        /// </summary>
        internal static string ParityLabel {
            get {
                return ResourceManager.GetString("ParityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Settings.
        /// </summary>
        internal static string PortSettingsMenuItem {
            get {
                return ResourceManager.GetString("PortSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string PortugueseOption {
            get {
                return ResourceManager.GetString("PortugueseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Log Files.
        /// </summary>
        internal static string PreviousLogMenuItem {
            get {
                return ResourceManager.GetString("PreviousLogMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QNX CCRT IP Address:.
        /// </summary>
        internal static string QnxIpAddressLabel {
            get {
                return ResourceManager.GetString("QnxIpAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCRT IP Addresses.
        /// </summary>
        internal static string QnxIpAddressMenuItem {
            get {
                return ResourceManager.GetString("QnxIpAddressMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Timeout (ms):.
        /// </summary>
        internal static string ReadTimeoutLabel {
            get {
                return ResourceManager.GetString("ReadTimeoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Device.
        /// </summary>
        internal static string RemoveDeviceLabel {
            get {
                return ResourceManager.GetString("RemoveDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        internal static string RemoveItemLabel {
            get {
                return ResourceManager.GetString("RemoveItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettingsLabel {
            get {
                return ResourceManager.GetString("SaveSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To QNX.
        /// </summary>
        internal static string SendToQnxColumn {
            get {
                return ResourceManager.GetString("SendToQnxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Windows CCRT Input Server ....
        /// </summary>
        internal static string StartingInputServer {
            get {
                return ResourceManager.GetString("StartingInputServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bits:.
        /// </summary>
        internal static string StopBitsLabel {
            get {
                return ResourceManager.GetString("StopBitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer Data:.
        /// </summary>
        internal static string TrailerDataLabel {
            get {
                return ResourceManager.GetString("TrailerDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer Length:.
        /// </summary>
        internal static string TrailerLengthLabel {
            get {
                return ResourceManager.GetString("TrailerLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows CCRT IP Address:.
        /// </summary>
        internal static string WinIpAddressLabel {
            get {
                return ResourceManager.GetString("WinIpAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Timeout (ms):.
        /// </summary>
        internal static string WriteTimeoutLabel {
            get {
                return ResourceManager.GetString("WriteTimeoutLabel", resourceCulture);
            }
        }
    }
}
