# FaultSchematicMap.properties
# 
# Mapping of fault identifiers to schematic documents.
#
NotAFault=
AirDoorNotLoweredFault=PLC/506422P22 Model (1).pdf
AirDoorNotRaisedFault=PLC/506422p01 Model (1).pdf
AirDoorStopPinProx1Activated=PLC/506422p05 Model (1).pdf
AirDoorStopPinProx2Activated=PLC/506422p10 Model (1).pdf
BadMessageFromCCDTranslator=
BoostPressureFailure=
CCDTranslatorNotAcceptingCommands=
CCDTranslatorNotResponding=
Check24VoltPowerSupply=
ControlPowerCircuitBreakerOpen=
CycleLimitExceeded=
CycleLimitWarning=
DCHoldingBrakeDisabled=
DripPanFullFault=
DriverInterfaceExtendedFault=
DriverInterfaceRetractedFault=
EntranceDoorFault=
ExhaustCarriageDriveFault=
ExhaustDoorLoweredFault=
ExhaustDoorRaisedFault=
ExhaustExtractSystemFault=
ExhaustStopPinProx1Activated=
ExhaustStopPinProx2Activated=
ExitDoorFault=
FifteenVoltDcPowerSupplyFault=
FireAlarm=
FRollSpeedsNotEqualWhenClutched=
FrontEBSDriveDisconnectOpen=
FrontEBSDriveNotLoweredFault=
FrontEBSDriveNotRaisedFault=
FrontEBSDriveOvercurrent=
FrontEBSDriveOverloadOpenFault=
FrontEBSMotorDriveFault=
FrontEBSMotorOvercurrent=
FrontElevatorLoweredFault=
FrontElevatorRaisedFault=
FrontHydraulicClutchDisengagedFault=
FrontHydraulicClutchEngagedFault=
