## defaultValues.properties
##
## Define default values for datatypes, and for specified tag names

## Data types
## Default values for each different data type.
type.short = 0
type.int = 0
type.bool = 0
type.byte = 0
type.float = 0.0
type.prompt = Blank
type.string = 
type.color = white
type.range = 0 0
type.faultkey = Empty
type.failurekey = Empty
type.testcomponentstatus = TestNotStarted

## Test results 
TestResultToPrint = /TestResults/Vehicle/emptytestresult.xml
OverallTest = TestPassed

## Selected tags
VINReadStatus = NoVIN
PromptBox1 = Blank
PromptBox2 = Blank

# test faults box
AllFailures = Empty
AllFaults = Empty

# Brake force defaults
LFForceTarget = 0 0
RFForceTarget = 0 0
LRForceTarget = 0 0
RRForceTarget = 0 0

LFForceDomain = 0 600 
RFForceDomain = 0 600
LRForceDomain = 0 600
RRForceDomain = 0 600 

MachineType3600 = 1
CurrentWheelbasePosition = 125.5

## This tag's type is "string", but the [axleimage] widget cannot accept "" as
## a value.
VehicleTypeImg = FWD

## LEDs
PowerSense = 0
VMESystemReady	= 0
PLCSystemIsReady = 0
PLCRackFault = 0
VehiclePresent = 0
CableConnect = 0
WCCFatalFault = 0

EnableAllRollDrives = 0
RollsUpElevDown = 0
RollsDownElevUp = 0
RearWheelDriveToPLC	= 0
FourWheelDrive = 0
AllWheelDrive = 0
ZerospeedToPLC = 0
TestInProgress = 0

LastCableConnected = left
