# keys for the bus communication panel and model
#

panel.buscomm.title=Bus Communication

buscommtablemodel.column.date=Date Stamp
buscommtablemodel.column.time=Time Stamp
buscommtablemodel.column.bus=Bus
buscommtablemodel.column.module=Module
buscommtablemodel.column.command=Command
buscommtablemodel.column.data.command=Command Data
buscommtablemodel.column.data.response=Response
buscommtablemodel.column.response=Resp
buscommtablemodel.column.fault=Fault

buscommtablemodel.error.request.missing=<html><font color="red">ERROR: Missing Request</font>
buscommtablemodel.error.ack.missing=<html><font color="red">ERROR: Missing ACK</font>
buscommtablemodel.error.response.missing=<html><font color="red">ERROR: Missing Response</font>
buscommtablemodel.error.request.missing.module=<html><font color="red">ERROR: Missing module {0}</font>
buscommtablemodel.error.request.missing.command=<html><font color="red">ERROR: Missing command{0}</font>
buscommtablemodel.error.response.mismatch.module=<html><font color="red">ERROR: module mismatch {0} != {1}: Mismatched modules.</font>
buscommtablemodel.error.response.mismatch.command=<html><font color="red">ERROR: command mismatch {0} + 0x40 != {1}: Mismatched modules.</font>
