ndbconfig.configerror.prefix = NdbUpdate Error
ndbconfig.configerror.nofileproxy = No File Proxy to be found
ndbconfig.button.ok = Retrieve
ndbconfig.label.retrieve=Retrieve the NDBConfig.xml file from the server
