#SecurityGuard configuration for password
#Wed Dec 08 15:00:48 EST 2004
login.admin=nqzva
config.role.user=Users have semi-restricted access to application configuration.
config.role.admin=Access to user administration and other restricted functions.
roles.admin=user admin
auth.timeout=300
