# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 10538 $

last_build_date=2009-10-06
core_build_today=5
cust_build_today=1
NAMETAG=Ccrt-C09100605
