# Configuration for CCRT client-based email messages
# (Configuration for com.atomicobject.util.Emailer)

email.default.body = This message was composed by the CCRT client system to deliver system data. PLEASE DO NOT RESPOND TO THIS MESSAGE.

email.dialog.address.title = Destination Address
email.dialog.address.request = Enter Email Address
email.error.title = Error sending email
email.send.error = Problem sending email, check the log file.
