# BaseConfiguration localization properties for all config panels.
# $Revision$

configpanel.label.gui=Client Logging
configpanel.label.crt=CRT Panel
configpanel.label.users=Users
configpanel.label.network=Network
configpanel.label.broadcast=Broadcast
configpanel.label.report=Report
configpanel.label.localization=Localization
configpanel.label.machine=Machine
configpanel.label.wheelbase=Wheelbase
configpanel.label.controllines=Control Lines
configpanel.label.buildrecord=Vehicle Build Record
configpanel.label.ztseditor=ZTS Build Record
configpanel.label.ndbupdate=Update NDBConfig File
configpanel.label.broken=BROKEN
configpanel.confirmchanges.message = Changes to panel have not been saved.
configpanel.confirmchanges.save = Save changes
configpanel.confirmchanges.discard = Discard changes
configpanel.confirmchanges.title = Unsaved changes

baseconfig.noresetlabel.label=Default setting not available

baseconfig.button.ok=Ok
baseconfig.button.ok.tip=Commit changes and dismiss the panel

baseconfig.button.apply=Apply
baseconfig.button.apply.tip=Commit changes and continue editing

baseconfig.button.cancel=Cancel
baseconfig.button.cancel.tip=Discard changes and set to current values

baseconfig.button.reset=Reset to Defaults
baseconfig.button.reset.tip=Reset all to default values










