# Keys for the controllines configuration panel
#
controllines.label.title=Control Lines
controllines.label.reset=Client must be restarted for changes to take effect.
controllines.label.warning=*** Warning changing control lines can drastically modify the behavior of the application. ***
controllines.button.validate=Validate
controllines.dialog.message=Invalid Tag name
controllines.dialog.title=Bad Tag Name

