# Localization of CrtPreviewer

crtfilefilter.description = Crt Files and Directories
jpgfilefilter.description = Jpg Files and Directories

saver.title = Save as JPEG Image...
opener.title = Open a Crt File

# menu bar
menubar.file = File
menubar.update = Update
menubar.validation = Validation
menubar.menuitem.open = open...
menubar.menuitem.print = print...
menubar.menuitem.save = save as...
menubar.menuitem.exit = exit
menubar.menuitem.reload = reload
menubar.menuitem.crtreport = Analyze CRT file
menubar.menuitem.ndbreport = Analyze NamedDataBroker

crtreport.title = CRT Report
crtreport.menubar.file = File
crtreport.menubar.menuitem.refresh = Refresh
crtreport.menubar.menuitem.close = Close
crtreport.error.message = Failed to report on CRT file
crtreport.error.nofile = No File loaded to produce report from
crtreport.error.title = CRT Report Error

ndbreport.title = NDB Report
ndbreport.textbox.datatype.label = Data Types
ndbreport.textbox.duplicate.label = Duplicate Tags
ndbreport.button.refresh = Refresh

frame.title = CrtPreviewer

joptionpane.error = Error
joptionpane.info = Information
joptionpane.warn = Warning
joptionpane.question = Question

save.overwrite = Overwrite existing file {0}?

reload.badnameddatabroker = Error in NDBConfig.xml
reload.warning = Tags not found in (NDBConfig.xml):
reload.invalid = Reload What?

doc.error.filenotfound = Cannot find file:
doc.error.couldnotconfigure = Cannot configure parser
doc.error.invalidformat = Invalid Format:

config.error.baddatarate = Crt File has invalid datarate
config.error.error = Error:
config.error.element = Element:
config.error.line = Line:






