# strings for the diagnostic view panel
diagnostic.label.plcbit=PLC Bit
diagnostic.label.faultmessage=Fault Message
diagnostic.label.description=Description
diagnostic.buttonlabel.schematics=Schematic

diagnostic.badfilechoice.message=No such file
diagnostic.badfilechoice.title=Invalid File

imagenotavailable=Image Not Available

# strings for errors in ExtendedDiagnosticViewer
diagnostic.loadproperties.error.title=Resource Bundle Not Found
diagnostic.loadproperties.error=Could not load the resource bundle.

# strings for the pdf viewer

diagnostic.pdfviewer.button.open=Open
diagnostic.pdfviewer.button.opennew=Open New
diagnostic.pdfviewer.button.openprev=Previous
diagnostic.pdfviewer.button.opennext=Next

diagnostic.readfile.text=Can't continue. Error reading the tag file.
diagnostic.readfile.title=Read file error

diagnostic.writefile.text=Can't continue. Error writing to the tag file.
diagnostic.writefile.title=Write file error
