# Keys for gui logging config panel
#
gui.level.label=Select Log Level
gui.level.tip=Choose a lower limit for log messages (any thing below will not be logged)

gui.location.label=Log Save Directory
gui.location.tip=Choose a save directory
gui.location.button=Change Directory
gui.location.button.tip=Changes the current save directory
gui.location.filechooser.title=Select Logging Directory

gui.amount.label=Number of Log Files
gui.amount.tip=Number of files in log rotation

gui.filesize.label=Size of file(s) in Kb
gui.filesize.tip=Size of each file in Kb
gui.filesize.info=log file(s) at

gui.sizepertest.label=Average Kb per test
gui.testperlog.info=Number of tests per log
