#
# Keys used at startup when detecting multiple instances
#
main.clientlock.title = Duplicate Client Instance
main.clientlock.text = Another instance of the CCRT client was detected. \n Only one instance may run at a time.
main.clientlock.button = Quit

# Keys used when starting the application
#

main.windowtitle=CCRT Client Application
main.selectserver.text = Enter the address of the EOL server, or select a simulation mode.
main.selectserver.title = Select Server
main.selectserver.button.connect = Server
main.selectserver.button.simulation = Simulation
main.selectserver.button.playback = Playback
main.selectserver.button.proxy = Proxy Server

#
# Strings for the dialog panel in Main for handling ConnectResponse failure 
#
main.connectrequest.title = Connect Request
main.connectrequest.denied.text = Server refused client ConnectRequest.
main.connectrequest.timeout.text = Timeout on client ConnectRequest to server.
main.connectrequest.otherfailure.text = ConnectRequest to server failed in an unkown manner.
main.connectrequest.exception.text=Failure connecting to server.

#
# Strings for the dialog panel in Main for handling absence of FTP server
#
main.ftpconfirm.text = No FTP or file server is available. If you choose\nto continue, the application will launch with\nrestricted functionality. The missing functionality\nwill not be available until you quit and restart\nthe application when the FTP or file server is available.

main.ftpconfirm.continue = Continue
main.ftpconfirm.quit = Quit
main.ftpconfirm.title = Warning


controller.brakeforce.noftp = No FTP server available at application launch. Start FTP server and restart app for brake force graphs.

controller.buscomm.noftp = No FTP server available at application launch. Start FTP server and restart app for bus communications data.

# locale chooser panel props
panel.localechooser.explanation=Choose a language for the application
panel.localechooser.ok=Ok

#
# shutdown the application messages
#
shutdown.title=Exiting
shutdown.text.initial=Shutting down application.............
shutdown.text.closing.demoframe=Closing demo frame.
shutdown.text.closing.driver=Closing driver display.
shutdown.text.closing.frontpanel=Closing front panel display.
shutdown.text.stopping.simserver=Stopping servlet engine.
shutdown.text.stopping.playback=Stopping playback daemon.
shutdown.text.stopping.log=Ending log.
shutdown.text.sending.terminate=Sending Terminate command to server.
shutdown.text.closing.panel=Closing panel...
