# These are the attributes of TestStep elements in server component
# configuration files which are ignored when processing for parameter
# report printing.
#
# The values of the keys are irrelevant. They keys themselves must match
# the ignored attributes exactly.
#
Units = ignored
Result = ignored
Description = ignored
Prompt1 = ignored
Prompt1Priority = ignored
Prompt2 = ignored 
Prompt2Priority = ignored
Timeout = ignored
PromptBox2 = ignored
PromptBox1 = ignored
