# This is used for the ResultsPanel
# $Revision$

button.reprint = Reprint
button.tooltip = Reprint the current report

reprint.printexception.title = Printer Communication Error
reprint.printexception.message = Error sending print job to printer.

reprint.printdriverexception.title = Output Error
reprint.printdriverexception.message = Cannot generate valid output.

reprint.ioexception.title = Input / Output Error

reprint.configurationexception.title = XML Error
reprint.configurationexception.message = Unusable XML.

reprint.printerdisabledexception.title = Printer Disabled
reprint.printerdisabledexception.message = The printers are disabled. This print job will be aborted.

# fileselected

fileselected.printdriverexception.title = Output Error
fileselected.printdriverexception.message = Cannot generate valid output.

fileselected.ioexception.title = Input / Output Error

fileselected.configurationexception.title = XML Error
fileselected.configurationexception.message = Unusable XML.

fileselected.illegalargumentexception.title = Invalid Remote File
fileselected.illegalargumentexception.message = Illegal Remote File was entered.

fileselected.badtext.title = Invalid Remote
fileselected.badtext.message = Invalid Remote was generated.

