# Localization for URLFileViewer related classes
# (Eg, LogViewer and BusCommViewer)

urllogviewer.email.request = Email address:
urllogviewer.email.title = Email

urllogviewer.refresh = Refresh
urllogviewer.save = Save

urllogviewer.load.error.title=Loading Log
urllogviewer.load.error.message=Failed to load server log

urllogviewer.columns.date = Date
urllogviewer.columns.who = Who
urllogviewer.columns.message = Message
urllogviewer.log.description=Log File and Directories
urllogviewer.log.error=LOG FILE ERROR

urlbuscommviewer.label.filterby=Filter By:
urlbuscommviewer.label.viewall=View All
urlbuscommviewer.button.filter=Filter

hostcomlogviewer.message.error=LOG FILE ERROR
hostcomlogviewer.message.select=SELECT A LOG
hostcomlogviewer.message.nolog=NO LOGS LOADED

hostcomlogviewer.label.logs=Log Events
hostcomlogviewer.label.who=Who
hostcomlogviewer.label.message=Message

urlfileviewer.loadwarning.start=CLIENT ERROR: File
urlfileviewer.loadwarning.end=failed to load

urlfileeditor.savewarning=CLIENT ERROR: Failed to write file






