label.startandboot=Bootup
label.vehicletest=Vehicle Test
vehicletest=VehicleTest
label.vehicletest.0=VehicleTest0
testcomps=Components
label.testcomps.brakes=Brakes
label.testcomps.absbrake=ABS Brakes
label.testcomps.airbag=Airbag
label.testcomps.cluster=Cluster
label.testcomps.cruise=Speed Control
label.testcomps.eatx=EATX
label.testcomps.emissions=Emissions
label.testcomps.skim=SKIM
modules=Modules
label.modules.absbrake=ABS Brakes
label.modules.airbag=Airbag 
label.modules.airbag.main=Airbag Main
label.modules.airbag.left=Airbag Left
label.modules.airbag.right=Airbag Right
label.modules.cluster=Cluster
label.modules.cruise=SpeedControl
label.modules.eatx=EATX
label.modules.emissions=Emissions
label.modules.skim=SKIM
machine=Machine 
label.machine.motorcontroller=Motor Controller 
label.machine.faults=Faults


