# Keys for the Users config panel
#
ztseditor.button.add=Add ZTS
ztseditor.button.add.tip=Add a ZTS record
ztseditor.button.change=Edit ZTS
ztseditor.button.change.tip=Change fields in a ZTS record
ztseditor.button.delete=Delete ZTS
ztseditor.button.delete.tip=Delete an existing ZTS record
ztseditor.newdialog.message=Enter name for this ZTS record
ztseditor.newdialog.title=Add a new Zts record
ztseditor.confirmdelete.title=Confirm Delete
ztseditor.confirmdelete.message=Delete zts: {0}?
ztseditor.editdialog.title=Change a ZTS field
ztseditor.editdialog.message.1=Data 1:
ztseditor.editdialog.message.2=Data 2:
ztseditor.property0.name=Description
ztseditor.property1.name=Wheelbase
ztseditor.property2.name=DriveType
ztseditor.property3.name=AxleType
ztseditor.property4.name=ABSType
ztseditor.property5.name=VehicleDynamicControl
ztseditor.property6.name=BodyStyle
ztseditor.property7.name=EngineType
ztseditor.property8.name=BrakeYear
ztseditor.property9.name=ABSPartNumber

ztseditor.configerror.nofileproxy=No file proxy
ztseditor.configerror.badurl=Bad URL
ztseditor.configerror.badresource=Bad resource
ztseditor.configerror.prefix=Zts editor configuration error

