# Keys for parameter report printer dialog
#
parameterreport.title=Parameter Report Printer
parameterreport.done=Done
parameterreport.print=Print Report
parameterreport.loading=Loading...
parameterreport.save=Save Report
parameterreport.refresh=Refresh

parameterreport.saveparams=Save
parameterreport.reportheader=Parameter Report
parameterreport.lastmodified=Date of last modification:
parameterreport.noconfigfiles=No configuration files found.

parameterreport.asktosave=Current parameter choices have not been saved. Save before continuing?
parameterreport.asktosavetitle=Unsaved Parameter Changes!
parameterreport.asktoexit=Current parameter choices have not been saved. Exit anyway?
parameterreport.asktoexittitle=Are you sure?

parameterreport.rfpnull=RemoteFileProxy cannot be null
parameterreport.resourcenotfound=No resource bundle found for
parameterreport.severeresourceerror=Grevious ResourceBundle misconfiguration:
parameterreport.listfailed=An error occured while trying to list the contents of one or more directories. See log file for details.
parameterreport.printerror=Parameter Report Error
parameterreport.filterdescription=Text Files
parameterreport.toomanyelementserr=Wrong number of child elements encountered searching for: 
parameterreport.badnode=ERROR: Bad Parameter
parameterreport.generatorerror=Error in Parameter Report Generator

remoteproxy.error.text=There is no path to the server right now.  This option is not available.
remoteproxy.error.title=No proxy to server available