#User Preferences for Burke Porter CCRT
#Fri Feb 08 19:52:12 GMT 2019
server.address.failsafe=172.16.250.5
controlline.drivermonitor.model=DisplayDriverMonitor
settings.clicktoexit.value=false
server.address=192.168.47.132
controlline.starttest.model=StartTest
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=US
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=E\:\\home\\branches\\GM\\Source\\Toyota\\Burke_PorterCCRT\\resources\\local\\report\\ticketlayout.xml
preference.language.iso=en
controlline.testresults.model=TestResultToPrint
settings.reportprinter.layout=E\:\\home\\branches\\GM\\Source\\Toyota\\Burke_PorterCCRT\\resources\\local\\report\\reportlayout.xml
settings.ticketprinter.printonpass=false
preference.units=English
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
settings.graphicsprinter.enabled=false
controlline.licensewarning.model=InvalidLicenseNotification
settings.reportprinter.printonpass=false
network.ftppassword=porter
network.useproxy=true
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
settings.reportprinter.xslt=E\:\\home\\branches\\GM\\Source\\Toyota\\Burke_PorterCCRT\\resources\\local\\report\\resultxform.xsl
server.use.stored.address=true
settings.ticketprinter.xslt=E\:\\home\\branches\\GM\\Source\\Toyota\\Burke_PorterCCRT\\resources\\local\\report\\resultxform.xsl
settings.reportprinter.printonfail=false
