# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 1.349 $

last_build_date=2005-08-05
core_build_today=1
cust_build_today=1
NAMETAG=Ccrt-C05080501
