# Keys for CRT panel config
#
crtconfig.label.readonly=CRT configuration is read-only or unavailable.
crtconfig.label.editorerror=Unable to create an editor for this view
crtconfig.reload.message.line1=Replacing current CRT config file with default settings.
crtconfig.reload.message.line2=This action cannot be undone.
crtconfig.reload.message.line3=Continue?
crtconfig.reload.title=Reload Defaults 
crtconfig.reloaderror.message=Failed to restore default config file from JAR.\n
crtconfig.saveerror.title=Save error
crtconfig.saveerror.message=Unable to save CRT config file

crtconfig.default.magic=DEFAULT
crtconfig.makeselection=Please select...
crtconfig.error.metadata=ERROR: Could not parse metadata from CRT file.
crtconfig.button.refresh=Refresh
crtconfig.author.name=Author:
crtconfig.version.name=Version:
crtconfig.button.new=New
crtconfig.button.delete=Delete
crtconfig.button.edit=Edit
crtconfig.popup.sourcelabel=Source:
crtconfig.popup.destlabel=New File:
crtconfig.popup.title=Create New CRT File
crtconfig.popup.filenameerror.message=Filename not valid.
crtconfig.popup.filenameerror.title=Filename Error
crtconfig.popup.filedupeerror.message=Source and destination files cannot be the same.
crtconfig.popup.noselection.message=You must make a selection to clone a new CRT file from.
crtconfig.popup.noselection.title=No selection made
crtconfig.popup.overwrite.message=Destination file exists.  Overwrite?
crtconfig.popup.overwrite.title=Overwrite File

crtconfig.popup.invalidsource.message=Please select a valid source file.
crtconfig.popup.invalidsource.title=Select a source file

crtconfig.popup.filecopyerror.message=Could not copy file into new location.
crtconfig.popup.filecopyerror.title=Copy Error

crtconfig.popup.confirmdelete.message=Are you sure you want to delete
crtconfig.popup.confirmdelete.title=Confirm File Delete
crtconfig.popup.designer=CrtDesigner

# CRTViewConfig object
crtviewconfig.error.usebackup=Using default CRT screen configuration -- unusable local config file has been backed up.
crtviewconfig.error.nobackup=Local CRT screen configuration unavailable.  Using read-only default configuration.
crtviewconfig.error.title=CRT View Config Error





