# brakeforce.properties
# This file contains the colors and attributes for configuring 
# BrakeForcePanel
#
# $Revision: 1.4 $

panel.brakeforce.xaxis.title=20 ms steps
panel.brakeforce.yaxis.title=Force
panel.brakeforce.data.name=Wheels

# panel.brakeforce.reset.key must be a single character.
# any extra characters will be ignored, and only the first char used.
# beware white space
panel.brakeforce.header.text=<html><center><FONT COLOR=black SIZE=-1>Drag mouse over Plot area to zoom. Click on labels to reposition.  Press ''{0}'' to reset.</FONT></center></html>

panel.brakeforce.footer.text=Drive Curve
panel.brakeforce.lf.label=Left Front
panel.brakeforce.rf.label=Right Front
panel.brakeforce.lr.label=Left Rear
panel.brakeforce.rr.label=Right Rear
panel.brakeforce.lt.label=Left Tandem
panel.brakeforce.rt.label=Right Tandem
panel.brakeforce.button.refresh=Load Data
panel.brakeforce.checkbox.markers=Display Markers
panel.brakeforce.loaddata.dialog.error.message=There was a severe problem\nloading the drive curve force data.\n\nYou might be able to get data\nif you try to load again, but\nprobably not.\n\nThe error detail is:\n

panel.brakeforce.loaddata.dialog.error.title=Problem loading data

#
# Brake Force Data Labels
#
panel.brakeforce.datalabels.start=Start
panel.brakeforce.datalabels.beginhp=Begin Horsepower
panel.brakeforce.datalabels.endhp=End Horsepower
panel.brakeforce.datalabels.beginspeedcontrol=Begin Speed Control
panel.brakeforce.datalabels.startbrakes=Start Brakes
panel.brakeforce.datalabels.startabs=Start ABS

panel.brakeforce.datalabels.lfreduction=LF Reduction
panel.brakeforce.datalabels.lfrecovery=LF Recovery
panel.brakeforce.datalabels.rfreduction=RF Reduction
panel.brakeforce.datalabels.rfrecovery=RF Recovery
panel.brakeforce.datalabels.lrreduction=LR Reduction
panel.brakeforce.datalabels.lrrecovery=LR Recovery
panel.brakeforce.datalabels.rrreduction=RR Reduction
panel.brakeforce.datalabels.rrrecovery=RR Recovery
panel.brakeforce.datalabels.ltreduction=LT Reduction
panel.brakeforce.datalabels.ltrecovery=LT Recovery
panel.brakeforce.datalabels.rtreduction=RT Reduction
panel.brakeforce.datalabels.rtrecovery=RT Recovery

panel.brakeforce.datalabels.endtest=End Test
