# This is used for the MachineSelectionPanel
# $Revision: 1.1 $

machine.pc.title = PC Machine
machine.vme.title = VME Machine

machine.pc.tooltip = Select if using a PC based machine
machine.vme.tooltip = Select if using a VME based machine

machine.warning = *** Application must be restarted for changes to take effect ***