# Keys for the menu labels and descriptions
#

# FrontPanel menu/toolbar action values
action.viewreport.name=Latest Test Report
action.viewreport.description=View the Latest Test Report

action.viewconfig.name=Configuration
action.viewconfig.description=View Configuration

action.viewbrake.name=Drive Curve
action.viewbrake.description=View Drive Curve

action.viewfront.name=Front Panel
action.viewfront.description=View Front Panel 

action.viewloss.name=Loss Compensation
action.viewloss.description=View Loss Compensation Panel

action.viewpower.name=Power Display
action.viewpower.description=View Power Display Panel

action.viewaboutserver.name=About Server
action.viewaboutserver.description=View Server Information

action.restartserver.savelogs.name=Restart Server - Save Logs
action.restartserver.savelogs.description=Restart Realtime Server and Save the System Logs
action.restartserver.nosavelogs.name=Restart Server - Nosave
action.restartserver.nosavelogs.description=Restart Realtime Server but Do Not Save System Logs
action.restartserver.role=user


action.shutdownserver.savelogs.name=Shutdown Server - Save Logs
action.shutdownserver.savelogs.description=Shutdown Realtime Server and Save the System Logs
action.shutdownserver.nosavelogs.name=Shutdown Server - Nosave
action.shutdownserver.nosavelogs.description=Shutdown Realtime Server but Do Not Save System Logs
action.shutdownserver.role=user

action.shutdownserver.name=Shutdown Server
action.shutdownserver.description=Shutdown Realtime Server
action.shutdownserver.role=user

action.exit.name=Exit
action.exit.description=Exit the application

action.about.name=About
action.about.description=About this application
action.splash.button.ok=Ok

action.busCommunication.name=Bus Communication
action.busCommunication.description=View bus communication for most recent test

action.plcdisplay.name=PLC Display
action.plcdisplay.description=View PLC Display information for system debugging

action.hostcomm.name=Host Communication
action.hostcomm.description=View host logs

action.viewparamreport.name=View Parameter Report
action.viewparamreport.description=View and print test parameters

action.logviewer.name=Log Viewer
action.logviewer.description=Browse and display server log files

action.viewclientlog.name=Client logs...
action.viewclientlog.description=Open, copy and email the client logs.

action.viewserverlog.name=Server logs...
action.viewserverlog.description=Open, copy and email the server logs.

action.login.name=Login...
action.login.description=Log in as a specific user

action.logout.name=Logout
action.logout.description=Logout the current user

action.viewbackup.config.name=Backup Configuration
action.viewbackup.config.description=Back up the configuration files

action.viewbackup.all.name=Backup All
action.viewbackup.all.description=Back up the whole CCRT directory

# FrontPanel menu items
frontpanel.menu.file=File
frontpanel.menu.file.new=New
frontpanel.menu.file.open=Open
frontpanel.menu.file.exit=Exit
frontpanel.menu.view=View
frontpanel.menu.diag=Diagnostics
frontpanel.menu.help=Help
frontpanel.menu.help.contents=Contents
frontpanel.menu.help.tutorial=Tutorial
frontpanel.menu.help.index=Index
frontpanel.menu.help.search=Search...
frontpanel.menu.help.updates=Updates
frontpanel.menu.help.information=Information
frontpanel.menu.help.about=About
frontpanel.menu.logs=Logs
frontpanel.menu.logs.select=Select...
frontpanel.menu.tools=Tools
frontpanel.menu.tools.drivecurves=Drive Curves
frontpanel.menu.tools.sysparams=System Parameters
frontpanel.menu.tools.backupconfig=Backup Configuration
frontpanel.menu.tools.backupall=Backup All
frontpanel.menu.diag.machine=Machine
frontpanel.menu.diag.machine=Machine

# Windows Menu
windowsmenu.jmenu.title=Windows
windowsmenu.jmenu.untitled=Untitled
