# Placeholder for localized names for paramters
# the key is a  parameter name and the value is its localized
# description
BaseBrake.LowWater=Low Water value
BaseBrake.OverallTest=Overall Test
BaseBrake.BrakeTarget=Brake Target
BaseBrake.CurrentForces=Current Forces
TransmissionComponent.Interesting=Interesting
TransmissionComponent.Wheels=wheels
TransmissionComponent.Name=Name
SpeedControl.NGC2190Delay=NGC2190 Delay
SpeedControl.J2190ConfigFile=J2190 Config File
SpeedControl.EngineONPrompt=Engine ON Prompt
