# Keys for report config panel
#
report.validate.button=Validate
report.validate.success=File Validated Successfully
report.validate.invalid.title=Invalid Format
report.report.validate.invalid.message=<html><font color=\"red\">Report Configuration will be currupt.</font></html>
report.ticket.validate.invalid.message=<html><font color=\"red\">Ticket Configuration will be currupt.</font></html>
report.filefilter.description=Printer Layout Files (*.xml)
report.report.layout.label=Report Printer Layout
report.report.layout.field.tip=Currently used report printer layout
report.report.layout.browse.label=Browse
report.report.layout.browse.tip=Change current report printer layout
report.ticket.layout.label=Ticket Printer Layout
report.ticket.layout.field.tip=Currently used ticket printer layout
report.ticket.layout.browse.label=Browse
report.ticket.layout.browse.tip=Change current ticket printer layout
report.layout.label=Printer Layout Configuration
report.config.label=Printer Configuration
report.report.tabbedpane.label=Report Printer Layout
report.ticket.tabbedpane.label=Ticket Printer Layout
