# Keys for VBR config panel
#
vehiclebuildrecord.button.load=Load
vehiclebuildrecord.button.new=New
vehiclebuildrecord.button.delete=Delete
vehiclebuildrecord.button.save=Save
vehiclebuildrecord.button.send=Send to Server
vehiclebuildrecord.label.title=Vehicle Build Record
vehiclebuildrecord.popup.checksaved.title=Vehicle Build Record Changed....
vehiclebuildrecord.popup.checksaved.message=Current values have changed, do you want to save them?
vehiclebuildrecord.popup.save.title=Save Filename
vehiclebuildrecord.popup.save.message=Enter filename to save as
vehiclebuildrecord.label.clientconnection=Misconfigured Vehicle Build Record Definition path
vehiclebuildrecord.label.ioexception=IO Error loading the VehicleBuild Record Definition
vehiclebuildrecord.label.ftpexception=Remote File Error loading the VehicleBuild Record Definition
vehiclebuildrecord.popup.nonconform=This file name does not conform to the standard, but will be saved anyway.
vehiclebuildrecord.popup.fieldlength=The length of this field must be {0} characters or less.
