# WheelBaseConfiguration localization properties for the WheelBaseConfiguration Panel.
# $Revision: 1.2 $

configModel.addedbodystyle=Enter body style
configModel.addeddescription=Enter description

configModel.column.modelyear=Model Year
configModel.column.bodystyle=Body Style
configModel.column.description=Description
configModel.column.wheelbase.english=Wheel Base (in)
configModel.column.wheelbase.metric=Wheel Base (cm)

pendantitempanel.vehiclelist.tooltip=List of cars associated with this pendant.
pendantitempanel.wheelbasebutton.tooltip=Modify the wheelbase size for this pendant.
pendantitempanel.removebutton.button=Remove
pendantitempanel.removebutton.tooltip=Remove a selected vehicle from this pendant.
pendantitempanel.pendantlabel.text=Wheelbase:
pendantitempanel.popup.label=New Wheelbase:
pendantitempanel.dialog.label=Change Wheelbase measure

#
# from baseconfig
#

wheelbaseconfiguration.resettodefaults.dialog.title=Bad URL
wheelbaseconfiguration.resettodefaults.dialog=Unable to reset data.  Could not load from URL:
wheelbaseconfiguration.applychanges.dialog.title=Error Saving File
wheelbaseconfiguration.applychanges.dialog=Unabled to save data.  Could not save to URL:
wheelbaseconfiguration.pendantinformationlabel=Pendant Configuration
wheelbaseconfiguration.leftinformationlabel=Wheelbase Configuration

wheelbaseconfiguration.addbutton.tooltip=Append selected vehicle to the selected pendant.
wheelbaseconfiguration.addbutton.exception.dialog=Corrupt Vehicle
wheelbaseconfiguration.addbutton.rownotselected.dialog=You must first select which vehicle in the table you wish to add to pendant.
wheelbaseconfiguration.addbutton.rownotselected.dialog.title=Row not selected
wheelbaseconfiguration.addbutton.incorrect.dialog=Vehicle cannot be added here.  Wheelbase measurements do not match.
wheelbaseconfiguration.addbutton.incorrect.dialog.title=Incorrect measurement

wheelbaseconfiguration.removevehiclebutton.tooltip=Removes selected vehicle from the list
wheelbaseconfiguration.removevehiclebutton.dialog=You must first select which vehicle in the table that you wish to remove.
wheelbaseconfiguration.removevehiclebutton.dialog.title=Row not selected
wheelbaseconfiguration.removevehiclebutton=Remove Vehicle

wheelbaseconfiguration.addvehiclebutton=Add Vehicle
wheelbaseconfiguration.addvehiclebutton.tooltip=Appends a blank vehicle to the vehicle list.

wheelbaseconfiguration.singlechar.label=? - single character

wheelbaseconfiguration.currentpositionstore.tooltip=Stores the machines current wheelbase to the selected vehicles wheelbase.
wheelbaseconfiguration.currentpositionstore.dialog.title=Manual Store
wheelbaseconfiguration.currentpositionstore.dialog=You must first select a vehicle in the table to store.
wheelbaseconfiguration.currentpositionstorebutton=Store
wheelbaseconfiguration.currentpositionlabel=Current Wheelbase Position
wheelbaseconfiguration.configerror.prefix=Screen not available
wheelbaseconfiguration.configerror.badfile=Invalid config file
wheelbaseconfiguration.configerror.badurl=Could not make FTP URL for path
wheelbaseconfiguration.configerror.nofileproxy=No remote file proxy available
wheelbaseconfiguration.configerror.badnumberbox=Could not create a NumberBox

