# This is the default resource bundle properties for
# all XmlWidgetPanel elements in the gui xml configuration
#
# $Revision: 1.1 $

panel.DriverMonitor.title=Driver Monitor

panel.FrontPanel.title=Rack Monitor 


