#These are properties serialized from an IA installer for use with an IA uninstaller.
#Tue May 26 17:57:02 GMT 2015
TEMP_DIR=\\tmp
\\=\\
EXTRACTOR_EXECUTABLE=L\:\\Ccrt-C12112806.exe
WIN_START_MENU=
INSTALLER_JDK_HOME=
PRODUCT_NAME=Burke Porter CCRT
MAC_CONTROL_PANELS=
INSTALLER_MERGE_MODULE=
STARTUP=
INSTALLER_JAVA_EXECUTABLE=E\:\\CCRT\\branches\\Common3700\\Source\\SGMW\\Burke_PorterCCRT\\jre
INSTALL_DRIVE_ROOT=\\
WIN_COMMON_PROGRAMS_MENU=
WIN_COMMON_START_MENU=
MAC_APPLE_MENU=
INSTALL_SUCCESS=SUCCESS
UNIX_USR_BIN=/usr/bin
EMPTY_STRING=
INSTALLER_JAVA_DOT_HOME=E\:\\CCRT\\branches\\Common3700\\Source\\SGMW\\Burke_PorterCCRT\\jreE\:\\Users\\derickso\\AppData\\Local\\Temp\\I1432659539\\Windows\\resource\\jre
WIN_COMMON_STARTUP=
UNIX_OPT=/opt
OVERWRITE_IA_CHMOD=false
IA_CLASSPATH=resources;tools.jar;endorsed/crimson.jar;lib/Serialio.jar;lib/activation.jar;lib/com.sun.net.ssl.jar;lib/ftpd.jar;lib/javax.servlet.jar;lib/jcchart.jar;endorsed/xalan.jar;lib/tools.jar;lib/org.mortbay.jetty.jar;lib/org.apache.jasper.jar;lib/jspComm.jar;lib/mail.jar;lib/ao-util.jar;lib/gnu-regexp.jar;ccrt-client.jar;resources/com/bepco/rtc/properties;resources/com/bepco/rtc/oldproperties;lib/servlet.jar;lib/jfreechart-0.9.20.jar;lib/jcommon-0.9.5.jar;lib/jrgwin32-1_06.jar;lib/acrobat-libs.jar;lib/edtftpj-1.5.0.jar;lib/avalon-framework-4.2.0.jar;lib/batik-all-1.6.jar;lib/commons-io-1.1.jar;lib/commons-logging-1.0.4.jar;lib/fop-hyph.jar;lib/fop-sandbox.jar;lib/fop.jar;lib/xmlgraphics-commons-1.0.jar
COMMA=,
;=;
CHOSEN_INSTALL_BUNDLE_LIST=Applica,Help
\:=;
EXTRACTOR_DIR=L\:\\
USER_INSTALL_DIR=E\:\\CCRT\\branches\\Common3700\\Source\\SGMW\\Burke_PorterCCRT
IA_DEBUG=true
/=\\
SYSTEM=/usr/local/bin
DESKTOP=E\:\\Users\\derickso\\Desktop
PARAM_1=E\:\\CCRT\\branches\\Common3700\\Source\\SGMW\\Burke_PorterCCRT
WIN_PROGRAMS_MENU=
CHOSEN_INSTALL_SET=Typical
NULL=
MACX_DOCK=
IA_CUSTOM_CODE_ZIP_SIZE=184789
PROGRAMS_DIR=E\:\\Users\\derickso
WIN_COMMON_DESKTOP=
CHOSEN_INSTALL_BUNDLE_3=
SHORTCUT_NAME=Link
CHOSEN_INSTALL_BUNDLE_2=Help
SYSTEM_DRIVE_ROOT=\\
CHOSEN_INSTALL_BUNDLE_1=Applica
USER_HOME=E\:\\Users\\derickso
USER_SHORTCUTS=Do_Not_Install
DOLLAR=$
WIN_WINDOWS=
WIN_QUICK_LAUNCH_BAR=E\:\\Users\\derickso
INSTALLER_TITLE=Burke Porter CCRT
MAC_EXTENSIONS=
UNIX_USER_HOME=E\:\\Users\\derickso
PRODUCT_VERSION_NUMBER=1.1.0.0
JAVA_HOME=E\:\\CCRT\\branches\\Common3700\\Source\\SGMW\\Burke_PorterCCRT\\jre
DO_NOT_INSTALL=Do Not Install
MACX_USER_APPLICATIONS=
CHOSEN_INSTALL_BUNDLE_NUM=2
FONTS=
MAC_PREFERENCES=
IA_INSTALLER_STATUS=SUCCESS
UNIX_USR_LOCAL_BIN=/usr/local/bin
MAC_CHEWABLE=
