//******************************************************************************
// Description:
// This class extends the functionality of the TestComponent to be able to
// retrieve force, acceleration, speed, ... arrays for performing analysis.
//
//===========================================================================
// Copyright (c) 2009- Burke E. Porter Machinery
// All Rights Reserved
//
// This file contains confidential information of Burke E. Porter Machinery
// and is not to be used in any way detrimental to the interests thereof.
// Unauthorized use, distribution, copying, or transmittal of this file in
// any way is strictly prohibited.
//===========================================================================
//
// LOG:
//    $Log: $
//
//******************************************************************************
// $NoKeywords: $
//==============================================================================
#ifndef Isuzu720AbsTc_h
#define Isuzu720AbsTc_h
//-----------------------------------------------------------------------------
#include "GenericABSTCTemplate.cpp"
//-----------------------------------------------------------------------------

template<class ModuleInterface>
class Isuzu720AbsTc : public GenericABSTCTemplate<ModuleInterface>
{
public:
    /** Class constructor */
    Isuzu720AbsTc();
    /** Class destructor */
    virtual ~Isuzu720AbsTc();
    /**
     * Sequence a test step.
     * <p><b>Category:</b> Utility
     * <br><p>
     * <b>Description:</b><br>
     * This is the method that will handle the execution of each test step that has been specified by the system for each
     * test objective that is passed to it.  This must be overloaded to execute the component tests.
     * <br><p>
     *
     * @param value    This is the value that was commanded by the test sequencer.
     * @return  The result of the test step that was executed.
     */
    virtual const string CommandTestStep(const string &value);

protected:
    /**
     * Analyze the forces generated during the dynamic park brake test
     * 
     * @return The status of the test step.
     */
    virtual const string AnalyzeDynamicParkBrake(void);

    /**
     * Read the brake arrays and calculate the park brake forces for each
     * of the vehicles wheels and analyze the data.
     *
     * @param brakeStart The starting sample index of the brake force array.
     * @param brakeEnd   The ending sample index of the brake force array.
     * @return The status of the operation.
     */
    virtual INT32 AnalyzeParkBrakeForces(INT32 brakeStart, INT32 brakeEnd);

    /**
     * Determine the configuration of the vehicle.
     * <p><b>Category:</b> Test Step
     * <br><p>
     * <b>Description:</b><br>
     * The parameters will be checked to determine if the vehicle is equipped with a four channel system.
     * 
     * @return Result of determining the system configuration
     */
    virtual string DetermineSystemConfiguration(void);

    /**
     * This sets up the GUI to prompt the driver to maintain
     * brake force in the target value.
     * 
     * @param brakeStart The starting sample of the park brake check.
     * @param brakeEnd   The ending sample of the park brake check.
     * @param tagPrefix  String added to the beginning of strings used to tag the
     *                   start and end of the force sampling interval
     * 
     * @return The status of the test.
     */
    virtual INT32 DynamicParkBrake(INT32 &brakeStart, INT32 &brakeEnd, const std::string &tagPrefix);

    /**
     * Place the module back into normal mode once testing is completed.
     * 
     * @return REsult of commanding the module to return to normal mode.
     */
    string EnterNormalMode(void);

    /**
     * Disable the brake force meter and updates.
     * 
     * @return Result of disabling the brake force meter.
     */
    string DisableForceMeter(void);

    /**
     * Perform the wheel speed sensor test and burnish the brakes.
     * 
     * @return Result of testing the wheel speed sensors and burnishing the brakes.
     */
    string IndividualSensorTest(void);

    /**
     * This test step is responsible for prompting the operator to
     * accelerate to the dynamic park brake arm speed. If we are testing 
     * the front axle alone (no drive axle), we will accelerate the rollers
     * via the MotorController
     * 
     * @return The status of the acceleration test step.
     */
    virtual const string TestStepAccelerateToParkBrakeSpeed(void);

    /**
     * This test step is responsible for prompting the driver 
     * to shift to neutral and applying the park brake to measure
     * the forces generated by the park brake
     * 
     * @return The status of the test step.
     */
    virtual const string TestStepDynamicParkBrake(void);

    /** 
     * Validate the park brake force of each wheel and update the display
     * with the result.
     *
     * @param roller  The roller to analyze the park brake force result for.
     * @param average The average park brake force for the specified wheel.
     * @return The status of the operation.
     */
    virtual INT32 ValidateParkBrakeForce(INT32 roller, float average);

	string PreRollBrakePedalPrime(void);

	string AbsPrime(void);



private:
    /**
     * Store the original drive axle prior to switching so it can be restored.
     * 
     * @param driveAxle Drive axle value to be stored.
     * 
     * @return Drive axle value to be restored after park brake testing is completed.
     */
    string& OriginalDriveAxle(const string *driveAxle = NULL);
    /** Original drive axle value.*/
    string m_originalDriveAxle;
    /** Array index where the dynamic park brake test started */
    int m_dynParkBrakeStart;
    /** Array index where the dynamic park brake test ended */
    int m_dynParkBrakeStop;
    /** Park brake force for each wheel during the dynamic park brake test. */
    FORCELIST m_parkBrakeForce;
};

//-----------------------------------------------------------------------------
#endif //Isuzu720AbsTc_h
