# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 10404 $

last_build_date=2009-06-15
core_build_today=8
cust_build_today=1
NAMETAG=Ccrt-C09061508
