#User Preferences for Burke Porter CCRT
#Tue Mar 29 14:31:40 EST 2011
server.address.failsafe=172.16.253.101
controlline.drivermonitor.model=DisplayDriverMonitor
settings.clicktoexit.value=false
server.address=172.16.253.101
controlline.starttest.model=StartTest
settings.reportprinter.name=EPSON TM-U220D Receipt
settings.ticketprinter.name=EPSON TM-U220D Receipt
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=CN
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\DCAC.ReportLayout.xml
preference.language.iso=zh
controlline.testresults.model=TestResultToPrint
settings.reportprinter.name.right=HP Officejet Pro K5400 Series
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\DCAC.ReportLayout.xml
settings.ticketprinter.printonpass=false
settings.printer.localize=true
preference.units=Metric
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
controlline.licensewarning.model=InvalidLicenseNotification
settings.graphicsprinter.enabled=false
settings.reportprinter.printonpass=true
network.ftppassword=porter
network.useproxy=false
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
server.use.stored.address=true
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Chinese.TicketReportLayout.xsl
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Chinese.TicketReportLayout.xsl
settings.reportprinter.printonfail=false
