#These are properties serialized from an IA installer for use with an IA uninstaller.
#Tue Nov 17 21:26:41 EST 2009
TEMP_DIR=C\:\\Documents and Settings\\DErickso\\Local Settings\\Temp
\\=\\
EXTRACTOR_EXECUTABLE=E\:\\CCRT\\Client\\Ccrt-C09100605.exe
INSTALLER_JDK_HOME=
WIN_START_MENU=C\:\\Documents and Settings\\DErickso\\Start Menu
PRODUCT_NAME=Burke Porter CCRT
MAC_CONTROL_PANELS=
INSTALLER_MERGE_MODULE=
STARTUP=C\:\\Documents and Settings\\DErickso\\Start Menu\\Programs\\Startup
INSTALLER_JAVA_EXECUTABLE=E\:\\home\\branches\\Toyota\\CCRT\\Burke_PorterCCRT\\jre\\bin\\java.exe
INSTALL_DRIVE_ROOT=E\:\\
WIN_COMMON_PROGRAMS_MENU=C\:\\Documents and Settings\\All Users\\Start Menu\\Programs
WIN_COMMON_START_MENU=C\:\\Documents and Settings\\All Users\\Start Menu
MAC_APPLE_MENU=
INSTALL_SUCCESS=SUCCESS
UNIX_USR_BIN=
EMPTY_STRING=
INSTALLER_JAVA_DOT_HOME=E\:\\home\\branches\\Toyota\\CCRT\\Burke_PorterCCRT\\jre
WIN_COMMON_STARTUP=C\:\\Documents and Settings\\All Users\\Start Menu\\Programs\\Startup
UNIX_OPT=
OVERWRITE_IA_CHMOD=false
IA_CLASSPATH=resources;tools.jar;endorsed/crimson.jar;lib/Serialio.jar;lib/activation.jar;lib/com.sun.net.ssl.jar;lib/ftpd.jar;lib/javax.servlet.jar;lib/jcchart.jar;endorsed/xalan.jar;lib/tools.jar;lib/org.mortbay.jetty.jar;lib/org.apache.jasper.jar;lib/jspComm.jar;lib/mail.jar;lib/ao-util.jar;lib/gnu-regexp.jar;ccrt-client.jar;resources/com/bepco/rtc/properties;resources/com/bepco/rtc/oldproperties;lib/servlet.jar;lib/jfreechart-0.9.20.jar;lib/jcommon-0.9.5.jar;lib/jrgwin32-1_06.jar;lib/acrobat-libs.jar;lib/edtftpj-1.5.0.jar;lib/avalon-framework-4.2.0.jar;lib/batik-all-1.6.jar;lib/commons-io-1.1.jar;lib/commons-logging-1.0.4.jar;lib/fop-hyph.jar;lib/fop-sandbox.jar;lib/fop.jar;lib/xmlgraphics-commons-1.0.jar
COMMA=,
;=;
CHOSEN_INSTALL_BUNDLE_LIST=Applica,Help,JNI
\:=;
EXTRACTOR_DIR=E\:\\CCRT\\Client
EXECUTE_EXITCODE=0
USER_INSTALL_DIR=E\:\\home\\branches\\Toyota\\CCRT\\Burke_PorterCCRT
IA_DEBUG=true
/=\\
SYSTEM=C\:\\WINDOWS\\system32
EXECUTE_STDOUT=\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>Echo ON \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>REM set env vars \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>for /F "tokens\=1-4 delims\=/ " %a in ('date /t') do (set weekday\=%a  & set month\=%b  & set day\=%c  & set year\=%d ) \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>(set weekday\=Tue  & set month\=11  & set day\=17  & set year\=2009 ) \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>REM Create the destination directory \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>set BACKUPDIR\=CCRT-20091117-BACKUP \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>Echo backup to CCRT-20091117-BACKUP \nbackup to CCRT-20091117-BACKUP\n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>REM Check if dir already exists \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>if exist \\CCRT-20091117-BACKUP goto CHECKDIR \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>GOTO COPYDIR \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>REM do the copy \n\nC\:\\Documents and Settings\\DErickso\\Local Settings\\Temp\\I1258511039\\Windows>xcopy /s /i E\:\\home\\branches\\Toyota\\CCRT\\Burke_PorterCCRT \\CCRT-20091117-BACKUP \n0 File(s) copied\n
DESKTOP=C\:\\Documents and Settings\\DErickso\\Desktop
PARAM_1=E\:\\home\\branches\\Toyota\\CCRT\\Burke_PorterCCRT
WIN_PROGRAMS_MENU=C\:\\Documents and Settings\\DErickso\\Start Menu\\Programs
CHOSEN_INSTALL_SET=Typical
MACX_DOCK=
NULL=
IA_CUSTOM_CODE_ZIP_SIZE=184415
PROGRAMS_DIR=C\:\\Program Files
WIN_COMMON_DESKTOP=C\:\\Documents and Settings\\All Users\\Desktop
EXECUTE_STDERR=
SHORTCUT_NAME=Shortcut
CHOSEN_INSTALL_BUNDLE_3=JNI
CHOSEN_INSTALL_BUNDLE_2=Help
CHOSEN_INSTALL_BUNDLE_1=Applica
SYSTEM_DRIVE_ROOT=C\:\\
USER_HOME=C\:\\Documents and Settings\\DErickso
USER_SHORTCUTS=Do Not Install
DOLLAR=$
WIN_WINDOWS=C\:\\WINDOWS
WIN_QUICK_LAUNCH_BAR=C\:\\Documents and Settings\\DErickso\\Application Data\\Microsoft\\Internet Explorer\\Quick Launch\\
INSTALLER_TITLE=Burke Porter CCRT
MAC_EXTENSIONS=
UNIX_USER_HOME=C\:\\Documents and Settings\\DErickso
PRODUCT_VERSION_NUMBER=1.1.0.0
JAVA_HOME=E\:\\home\\branches\\Toyota\\CCRT\\Burke_PorterCCRT\\jre
DO_NOT_INSTALL=Do Not Install
CHOSEN_INSTALL_BUNDLE_NUM=3
MACX_USER_APPLICATIONS=
FONTS=C\:\\WINDOWS\\Fonts
MAC_PREFERENCES=
IA_INSTALLER_STATUS=SUCCESS
UNIX_USR_LOCAL_BIN=
MAC_CHEWABLE=
