
# This describes/defines how Playback server responds to command requests

# The playback server will use this in place of defaulting to success

ConnectRequest = Success
KeepAlive = Success
ReturnFailure = Failure

