# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 9756 $

last_build_date=2009-05-21
core_build_today=3
cust_build_today=1
NAMETAG=Ccrt-C09052103
