# keys for report management
#
reportmanager.error.reportlayout=Report layout is corrupt, using default.
reportmanager.error.reportfallback=Could not load default report layout.  Report printing disabled.
reportmanager.error.reporttitle=Report Layout Corrupt
# ticket layout
reportmanager.error.ticketlayout=Ticket layout is corrupt, using default.
reportmanager.error.ticketfallback=Could not load default ticket layout.  Ticket printing is disabled.
reportmanager.error.tickettitle=Ticket Layout Corrupt
# report engine config error
reportmanager.error.enginetitle=Report Engine Failure
reportmanager.error.enginebuild=Reporting engine could not be started.  Report and ticket printing disabled.
# report engine Xsl Transform file
# xslprintertransformfile=resultTicketForm.xsl
xslprintertransformfile=resultxform.xsl
