
# PLCmap.properties
# LENGTH TEMPLATE =  ~43 chars
# FOR FORD FLATROCK 506422

AirDoorNotLoweredFault = I:020/10
AirDoorNotRaisedFault = I:020/07
ExhaustDoorLoweredFault = I:021/03
ExhaustDoorRaisedFault = I:021/02
FrontRetainingRollsLoweredFault = I:020/06
FrontRetainingRollsRaisedFault = I:020/05
IntermediateRetainingRollsLoweredFault = I:020/12
IntermediateRetainingRollsRaisedFault = I:020/11
LeftFrontRollMotorDisconnectOpen = I:011/10
LeftFrontRollMotorDriveFault = I:010/01
LeftRearRollMotorDisconnectOpen = I:011/12
LeftRearRollMotorDriveFault = I:010/03
LeftStopPostLoweredFault = I:020/02
LeftStopPostRaisedFault = I:020/01
MotorTaskHearbeatFault = N16:9/3
PanelEStopPushbuttonDepressed = I:011/00, I:011/01
PanelTemperatureHighWarning = I:011/02
PLC5Rack1Fault = S:7/1
PLC5Rack2Fault = S:7/2
PLC5Rack3Fault = S:7/3
PLCBatteryLowFault = S:10/00
RetainingRollLockDisengagedFault = I:020/13
RetainingRollLockEngagedFault = I:020/13  
RightFrontRollMotorDisconnectOpen = I:011/11
RightFrontRollMotorDriveFault = I:010/02
RightRearRollMotorDisconnectOpen = I:011/13
RightRearRollMotorDriveFault = I:010/04
RightStopPostLoweredFault = I:020/04
RightStopPostRaisedFault = I:020/03
RollMotorPowerSupplyAlarmOn = I:010/00
SolenoidCircuitBreakerOpenPanel = I:011/03
SolenoidFuseOpenJBox = I:020/00
SystemAirPressureLowFault = I:021/00
WBPositionValueOutOfLimit = N13:0
WheelbaseMotorDisconnectOpen = I:011/14
WheelbaseMotorDriveFault = I:010/05
WheelbasePositioningFault = B3/201, B3/38, B3/18

