# This properties file contains all the information strings that
# relate to the configuration of our printing system.
#
# $Revision: 10700 $

printer.textfield.tooltip=Name of the current printer being used
printer.changebutton.text=Change Printer
printer.changebutton.tooltip=Changes the current printer
printer.testpagebutton.text=Print Test Page
printer.testpagebutton.tooltip=Print a test page using the current printer
printer.disablecheckbox.text=Enable printer
printer.disablecheckbox.tooltip=Disable / Enabled this printer
printer.enabletestpasscheckbox.text=Enable for pass
printer.enabletestpasscheckbox.tooltip=Enable this printer for OverallTest pass
printer.enabletestfailcheckbox.text=Enable for fail
printer.enabletestfailcheckbox.tooltip=Enable this printer for OverallTest fail

printer.textfield.noprinter=No Printer Associated
printer.combobox.noprinter=No Printer(s) Available
printer.dialog.change=Change
printer.dialog.cancel=Cancel
printer.dialog.text=Select the Printer
printer.side.left=Left
printer.side.right=Right

system.reportprinter.text=Report Printers:
system.ticketprinter.text=Ticket Printers:
system.graphicsprinter.text=Graphics Printer:

system.flattexttestpage.noprinter.error=No such print service found
system.flattexttestpage.nullresource.error=Print page location could not be found
system.flattexttestpage.success=Print Job was successfully sent.
system.flattexttestpage.noprintername.error=No Printer name was supplied
system.flattexttestpage.testpagelocation.error=Cannot locate test page
system.flattexttestpage.printdriver.error=Print Driver cannot generate valid output
system.flattexttestpage.badjob.error=Current Printer cannot accept the job

system.graphicstestpage.noprinter.error=No Such Print Service Found
system.graphicstestpage.success=Print Job was successfully sent.
system.graphicstestpage.noprintername.error=No Printer name was supplied
system.graphicstestpage.testpagelocation.error=Cannot locate test page
system.graphicstestpage.badjob.error=Current Printer cannot accept the job

system.popup.warningtitle=Warning
system.popup.infotitle=Information

printer.font.name=Courier
printer.font.size=10
printer.font.lineheightmultiplier=0.70
printer.font.wordwrapaddchars=10
printer.font.charsperline=default
printer.font.extracharsperline=10