#
# Properties file for text prompts.
#
# These are the real prompts
AbortEngineTempTooHigh = ABORT - Engine Temperature Too High!
AbortPcmCommFailure = ABORT - No ECM Communication!
AbsLampTest = ABS lamp test, abort if lamp not blinking
AbsPrime = ABS Prime Step, Do Not Release Brake Pedal
ABSTest = Peforming ABS test
AbsTestPleaseWait = ABS test, please wait
Accelerate = Accelerate
AccelerateAboveBrakeArmSpeed = Accelerate to brake speed
AccelerateAboveMph = Accelerate above {0} {1}
AccelerateAboveMphAndHold = Accelerate above {0} {1} and hold
AccelerateAtWOT = Accelerate at Wide Open Throttle
AccelerateAtWOTCheckKickdown = Accelerate at WOT and watch for kickdown
AccelerateModeratelyToTargetSpeed = Accelerate to target moderately and hold
AccelerateThrottleInGreen = Accelerate with throttle in green band
AccelerateTo2ndGearThrottleInGreen = Accelerate to 2nd gear with throttle in green band
AccelerateTo3rdGear = Accelerate to 3rd gear
AccelerateTo40KPH = Accelerate to 40km/h (25mph)
AccelerateToTargetSpeed = Accelerate to the target speed
AccelerateToTargetSpeedInD6 = Accelerate to the target speed in D6
Accept = Accept
ActivateHorn = Activate vehicle horn
AirbagBeingTested = Airbag being tested, please wait
AirbagDischarging = Airbag discharging, time remaining {0}
AirbagFault = Airbag fault, test aborted
AirConditioningIsOn = Air conditioning is on
ApplyBrake = Apply brake pedal
ApplyBrakeShiftToReverse = Apply brake and shift to reverse
ApplyParkBrake = Apply park brake
AtFullThrottle = At full throttle
AtHalfThrottle = At half throttle
AtModerateThrottle = At moderate throttle
AutomaticTransmission = Automatic Transmission
AxleCheck = Axle Test: Machine Driving Rear Roller
BaseBrakeInitialize = Initializing The Base Brake Component
BlockByPFS = Blocked by PFS
BrakeHard = Brake hard
BrakeModeratelyInGreenBand = Brake moderately in green band
BrakesAreNotOn = Brakes are not on
BrakeTest = Brake test
BrakeToMph = Brake to {0} {1}
BrakeToStop = Brake to stop
BrakingToHard = Braking to hard
CableConnected = Cable connected
CableDisconnected = Cable not connected, connect cable
CaseLearnInProgress = CASE Learn in progress
CheckDaytimeRunningLights = Check daytime running lights
CheckForStableSpeed = Check for stable speed
CheckingO2Sensors = Analyzing O2 Sensors - {0}% Complete
CheckingVehicle = Checking vehicle
CheckRollingDoorLocks = Check rolling door locks
CheckSpeedometer = Check speedometer
CheckTransmissionShifting = Check transmission shifting
CheckVehicleConnector = Check vehicle connector
ClearToExit = Machine Home - Exit Booth
CoastDownToMph = Coast down to {0} {1}
CoastDownToStop = Coast down to stop
CoastDownToTargetSpeed = Coast down to target speed
CommunicationBusProblem = Communication bus problem
ConnectCable = Connect cable
ConnectMimamoriCable = Connect Mimamori Cable
CouldNotStartSystem = Failed to start up system
CycleLossCompensationSwitch = Cycle the Loss Compensation switch
DecreaseThrottle = Decrease throttle
DelayBeforeDtcRead = Waiting to read DTCs
DelayBeforeTapPrompt = Waiting before brake tap prompt
DetectedVehiclePresent = Vehicle present detected
DisconnectCable = Disconnect cable
DoesSteeringWheelEffortIncrease = Does steering wheel effort increase? P/F
DoNotShift = Do not shift
DoYouWantToJounceTest = Do you want to jounce test
EatxInLimpIn = Eatx in limp-in
EatxMustSee3rd = Eatx must see 3rd gear
EatxMustSee4th = Eatx must see 4th gear
EatxMustSee5th = Eatx must see 5th gear
EatxMustSeeLockup = Eatx must see lockup
EatxOilTooHot = Eatx oil too hot
EatxTest = Eatx test
EatxTests = Eatx Test
EgrTest = EGR test
EmissionsInitialization = Initializing Emissions Module
EmissionsTest = Emissions Test
EmissionsTesting = Emissions testing
EngineMustIdle = Engine must be idling for this test
EngineOffIgnitionOn = Engine off, ignition on
EngineOffIgnitionOff = Engine off, ignition off
EnterVIN = Scan Barcode
EnterYesOrNo = Enter Y/N
EStopPressed = Cable connected
ExhaustEvalInProgress = Position exhaust sensor boom in exhaust pipe
FatalFault = Fatal fault, check machine
FootOffBrake = Remove foot from brake pedal
FootOnBrake = Place foot on brake pedal
LeftFootOnBrake = Apply and hold brake with left foot
GoodScan = Barcode Scanned, build data loaded
HighSpeedChimeTest = High speed chime test
HighSpeedSensorTest = Performing high speed sensor test
HoldThrottleSteady = Hold throttle steady
IncreaseThrottle = Increase throttle
Initialize = Initializing vehicle modules
InputDriverID = Please input your driver number
InvalidBroadcastTestcode = Invalid broadcast testcode
InvalidPFSStatus = Invalid PFS status
IsODLampOff = Is overdrive lamp off? Y/N
IsTracLockLampOff = Is TRAC OFF lamp off? Y/N
IsTracLockLampOn = Is TRAC OFF lamp on? Y/N
JounceAboutToBegin = Jounce test about to begin
JounceComplete = Jounce test complete
JounceStarted = Jounce test has started
KeyOff = Turn ignition off
KeyOn = Turn ignition on
KickDownTo1st = Kick down to 1st, half throttle
Launching = Launching tasks, please wait
LeftFrontRollFailed = Left front roll failed to accelerate
LeftRearRollFailed = Left rear roll failed to accelerate
LiftFootPunchThrottle = Lift foot briefly then, punch and release throttle
LiftFootShiftTo1st = Lift foot from accelerator, shift to 1st gear
LoadingTestParameters = Loading test parameters
LossCompensationAccelToWarmup = Accelerating to warmup speed
LossCompensationBrakingRolls = Loss Compensation braking rolls
LossCompensationComplete = Loss Compensation complete
LossCompensationInProgress = Loss Compensation in progress
LossCompensationSwitchOff = Turn Loss Compensation switch off
LossCompensationTest = Loss Compensation Test
LossCompensationWaitForStop = Waiting for rollers to stop
LossCompensationWarmup = Performing Loss Compensation warmup
LowerElevators = Lower elevators
LowerRetainers = Lower retainers
MaintainBrake = Maintain brake
MaintainSpeed = Maintain speed
MaintainThrottleEatxMustSeeLockup = Maintain throttle, eatx must see lockup
MaintainThrottleInGreenBand = Maintain throttle in green band
ManualMode = Manual mode
ManualTransmission = Manual transmission
MessageTimeout = Message timeout
NewVINReceived = New VIN received
OverallPassOrFail = Press pass or fail for overall test
OverSpeed = Overspeed
PartTimeLampOff = Part time lamp off
PartTimeLampOn = Part time lamp on
PassOrFail = Enter Pass or fail
PassOrFail4WDIndicator = Enter P/F for 4WD indicator light
PcmPNCorrect = Is this PCM part number correct? Y/N
PerformingFinalTest = Performing final module tests
PerformingFinalTesting = Performing final testing
# PerformingFinishUp = Performing FinishUp
PerformingFinishUp  =  Performing module finishup
# PerformingFinishUp = Performing module finishup
PerformingFinishUp  =  Performing module finishup
PerformingQuickLearn = Performing Quicklearn
PfsAbortStatus = Vehicle in Abort status from PFS
PfsBlock = Vehicle is Blocked by PFS
PfsShipStatus = Vehicle in Ship status from PFS
PhaseFail = Test Phase Failed
PhasePass = Test Phase Passed
PlaceTiltColumnFullDown = Place tilt column full down
PlaceTiltColumnFullUp = Place tilt column full up
PleaseRemoveVehicle = Please remove vehicle
PleaseWait = Please wait
PowerSteeringTest = Power steering test
PressAbort = Press abort
PressAndReleaseClutch = Press and release clutch
PressButtonToStartTest = Press GREEN CLEAR button to start test
# PressSpeedoButtonAtSpeed = Press SPEEDO TEST button at test speed
PressSpeedoButtonAtSpeed  =  Press PASS TEST button at 40km/h (25mph)
PressThrottle = Throttle Test: depress throttle
PressUpArrow = Press up arrow
PressUpArrowWhenReady = Press up arrow when ready
PrintingTestReport = Printing test report
PushAcceleratorToFloor = Press accelerator pedal to the floor
RaiseElevators = Raise elevators
RaiseRetainers = Raise retainers
RedBrakeLampOffPorF = Is red brake lamp off? P/F
ReduceThrottleUntil34Shift = Reduce throttle until 3 to 4 shift occurs
ReduceThrottleUntilUpshift = Reduce throttle until upshift occurs
ReleaseParkBrake = Release the Park Brake
ReleaseThrottle = Remove foot from throttle
ReleaseThrottleShiftNeutral = Release throttle, shift to neutral
RemoveAirbagFusesAndAbort = Remove airbag fuses and abort the test
RemoveFootFromAccelerator = Remove foot from accelerator
RemoveFootFromClutch = Remove foot from clutch
ReseatCable = Reseat cable
RetestYesOrNo = Retest?  Yes=CLEAR / No=TEST
ReverseTest = Reverse test
RightFrontRollFailed = Right front roll failed to accelerate
RightRearRollFailed = Right rear roll failed to accelerate
Sampling = Sampling
Select3rd = Select 3rd position and, wait a minimum of 2 seconds
SelectLow = Select low position and wait a minimum of 2 seconds
SelectOD = Select overdrive
SelectTracLockSwitch = Cycle trac lock switch
SelectTransmissionType = Select transmission type
SendingTestResults = Sending test results
SetOperatorConsoleTo4WD = Set operator console to 4WD
SettingUpABSModule = Setting up ABS module
SettingUpCommBus = Setting up communication bus
SettingUpEatxModule = Setting up eatx module
SettingUpEngineController = Setting up engine controller
SettingUpOverland = Setting up overland
ShiftAutostick1 = Shift to Autostick 1
ShiftAutostick2 = Shift to Autostick 2
ShiftAutostick3 = Shift to Autostick 3
ShiftAutostick4 = Shift to Autostick 4
ShiftLeverTest = Shift lever test
ShiftOutOf4WD = Shift out of 4WD
ShiftTo4HiLock = Shift to 4 hi lock
ShiftToDrive = Shift the transmission to D6
ShiftToGear = Shift To {0} {1}
ShiftToGearAndAccelerate = Shift To {0} {1} and accelerate
ShiftToLow = Shift the transmission to Low
ShiftToNeutral = Shift the transmission to neutral
ShiftToNeutralApplyParkBrake = Shift to neutral, Apply park brake
ShiftToPark = Shift the transmission to Park
ShiftToParkApplyParkBrake = Shift to Park, apply park brake
ShiftToParkOrNeutral = Shift the transmission to Park or Neutral
ShiftToReverse = Shift the transmission to reverse
ShiftToThird = Shift the transmission to 3rd
ShiftTo1 = Move Shift Lever To 1
ShiftTo2 = Move Shift Lever To 2
ShiftToD3 = Move Shift Lever To D3
ShiftToD4 = Move Shift Lever To D4
ShiftToD6 = Move Shift Lever To D6
ShiftTransferCase = Shift transfer case to {0} {1}
SimulationSwitchOff = Turn the Simulation switch off
SlowDownToMph = Slow down to {0} {1}
SlowDownToTargetSpeed = Slow down to the target speed
SoundLevelEvalInProgress = Sound level analysis in progress
SpeedControlCancel = Press and hold the cancel button
SpeedControlCheckLamp = Check cruise on lamp
SpeedControlMustBeIn3rd = Must be in 3rd gear to set
SpeedControlOff = Press cruise off button
SpeedControlOn = Press cruise on button
SpeedControlPressClutch = Press the clutch
SpeedControlPressFail = If cruise does not operate, press fail
SpeedControlResume = Press cruise resume button
SpeedControlSet = Press cruise set button
SpeedControlTapBrakes = Tap brakes
SpeedControlTest = Cruise test
SpeedProSteeringTest = Speed proportional steering test
StartVehicle = Start vehicle
SystemResetting = System resetting
SystemRestarting = Restarting system, please wait
TcmFaultsDetected = ABORT - TCM Faults
TestAborted = Test aborted
TestCompleted = Test completed
TestFailed = Test failed
TestPassed = Test passed
TestSoftwareFail = Error Sequencing Drive Curve
TestTimeout = Test time out
ThrottleIsHigh = Throttle is high
TimeRemaining = Time remaining {0}:{1}
TorqueConverterLockupTest = Torque converter lockup test
TractionControlTest = Traction control test
TransferCaseTest = Transfer case test
TransmissionShouldShiftTo1st = Transmission should shift to 1st at or above {0} {1}
TransmissionShouldShiftTo2nd = Transmission should shift to 2nd at or above {0} {1}
TRDLinkTest = TRD link test
TurnEngineOffAndKeyOn = Engine Off Ignition On
TurnLossCompensationSwitchOff = Turn Loss Compensation switch off
TurnOffACFanDefrost = Turn OFF A/C, Fan and Defrost
TurnOffDefrost = Turn off defrost
TurnOnAc = Turn on Air Conditioning
TurnSteeringWheel45Clockwise = Turn steering wheel to 45° clockwise
TurnSteeringWheel45CounterClockwise = Turn steering wheel to 45° counter clockwise
TurnSteeringWheelLeftRightCenter = Turn steering wheel left right center
TurnSteeringWheelLeftRightLeft = Turn steering wheel left right left
TurnSteeringWheelToCenter = Turn steering wheel to center
TurnSteeringWheelToLeft = Turn steering wheel to left
TurnSteeringWheelToRight = Turn steering wheel to right
TurnTrackLockOff= Trun off the TRAC LOCK switch
TurnTrackLockOn= Turn on the TRAC LOCK switch
UpShift = Up shift
VacuumLeakTest = Vacuum leak test
VehicleInShipStatus = Vehicle in ship status
VehicleNotInNeutral = Vehicle is not in neutral
VINNotFound = VIN not found
VinMismatch = PCM VIN does not match scanned VIN
VinMismatchPrompt = TCM VIN does not match scanned VIN
WaitForEngineTemp = Wait for engine temp to reach {0}
WarmingUpBearings = Warming up bearings
WarmUp = System warmup, please wait
WccBadCheckSum = Bad Checksum Received From WCC
WccNoInfo = No Vehicle information for VIN {0}
WccNoResponse = No response from WCC
WccSentNAK = Bad message sent to WCC
WccUnknownMessage = Unknown message received from WCC
WheelbaseIncorrect = Waiting for wheelbase
ZeroSpeed = Brake To Stop
#System Fault Prompts
PowerSenseLost = Power Sense Lost To PLC
RackFault = PLC Rack Fault Detected
AccelerateToReverseTargetSpeed = Accelerate in Reverse to target speed
NeutralFootOffBrake = Shift to neutral, foot off brake
RemoveFootFromBrake = Remove foot from brake pedal
VerifyTransmissionShifting = Verify transmission shifting
VerifyIdleRPM = Verify engine RPM (Pass/Fail)
WaitForAbsToSettle = Wait for ABS to be ready, Foot off Brake
PerformingFinishUp  =  Performing module finishup
PerformingFinishUp  =  Performing module finishup