#User Preferences for Burke Porter CCRT
#Sat Aug 28 15:11:37 GMT 2010
server.address.failsafe=172.16.250.3
controlline.drivermonitor.model=DisplayDriverMonitor
settings.clicktoexit.value=false
server.address=192.168.1.1
controlline.starttest.model=StartTest
settings.reportprinter.name=EPSON TM-U220 Receipt
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=BR
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ticketlayout.xml
preference.language.iso=pt
controlline.testresults.model=TestResultToPrint
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\reportlayout.xml
settings.printer.localize=true
settings.ticketprinter.printonpass=false
preference.units=Metric
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
controlline.licensewarning.model=InvalidLicenseNotification
settings.graphicsprinter.enabled=false
settings.reportprinter.printonpass=true
network.useproxy=false
network.ftppassword=porter
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
server.use.stored.address=true
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\VolkswagenReportLayout.xsl
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\resultxform.xsl
settings.reportprinter.printonfail=true
