# Keys for the Users config panel
#
users.button.add=Add User
users.button.add.tip=Adds a new user
users.button.change=Change User Name
users.button.change.tip=Change's the name of an existing user
users.button.delete=Delete User
users.button.delete.tip=Delete an existing user
users.button.setpass=Set Password
users.button.setpass.tip=Sets the password of the selected user
users.button.roles=Edit Roles
users.button.roles.tip=Assign roles to the selected user
users.namedialog.message=Enter new username:
users.namedialog.title=Add a user
users.passdialog.title=Change password
users.passdialog.message.1=Enter new password:
users.passdialog.message.2=Re-enter password:
users.passdialog.error.title=Password Mismatch
users.passdialog.error.message=Password entries must be identical.
users.confirmdelete.title=Confirm Delete
users.confirmdelete.message=Delete user: {0}?
users.invaliddelete.error=Cannot delete currently logged-in user: {0}
users.invaliddelete.title=Cannot delete user
users.invalidedit.error=Cannot edit roles for currently logged-in user: {0}
users.invalidedit.title=Cannot change user roles
users.roledialog.title=Assign Roles
users.roledialog.message=Specify the roles associated with this user:
users.roledialog.addbutton.label=>>
users.roledialog.addbutton.tip=Add the selected role(s) to the current user
users.roledialog.removebutton.label=<<
users.roledialog.removebutton.tip=Remove the selected role(s) from the current user
users.roledialog.currentlist.label=Assigned
users.roledialog.currentlist.tip=Select roles that you wish to remove
users.roledialog.availlist.label=Available
users.roledialog.availlist.tip=Select roles that ypu wish to add
users.roledialog.descriptionbox.tip=Description of the selected role

