#These are properties serialized from an IA installer for use with an IA uninstaller.
#Fri May 20 09:30:27 EDT 2011
TEMP_DIR=C\:\\Documents and Settings\\rsmith\\Local Settings\\Temp
\\=\\
EXTRACTOR_EXECUTABLE=O\:\\Software-EOL\\CCRT\\ClientBuilds\\BetaClientBuilds\\Ccrt-C11051302.exe
WIN_START_MENU=C\:\\Documents and Settings\\rsmith\\Start Menu
INSTALLER_JDK_HOME=
PRODUCT_NAME=Burke Porter CCRT
MAC_CONTROL_PANELS=
INSTALLER_MERGE_MODULE=
STARTUP=C\:\\Documents and Settings\\rsmith\\Start Menu\\Programs\\Startup
INSTALLER_JAVA_EXECUTABLE=C\:\\Documents and Settings\\rsmith\\Desktop\\Tata.Oremco.Burke_PorterCCRT\\jre\\bin\\java.exe
INSTALL_DRIVE_ROOT=C\:\\
WIN_COMMON_PROGRAMS_MENU=C\:\\Documents and Settings\\All Users\\Start Menu\\Programs
WIN_COMMON_START_MENU=C\:\\Documents and Settings\\All Users\\Start Menu
MAC_APPLE_MENU=
INSTALL_SUCCESS=SUCCESS
UNIX_USR_BIN=
EMPTY_STRING=
INSTALLER_JAVA_DOT_HOME=C\:\\Documents and Settings\\rsmith\\Desktop\\Tata.Oremco.Burke_PorterCCRT\\jre
WIN_COMMON_STARTUP=C\:\\Documents and Settings\\All Users\\Start Menu\\Programs\\Startup
UNIX_OPT=
OVERWRITE_IA_CHMOD=false
IA_CLASSPATH=resources;tools.jar;endorsed/crimson.jar;lib/Serialio.jar;lib/activation.jar;lib/com.sun.net.ssl.jar;lib/ftpd.jar;lib/javax.servlet.jar;lib/jcchart.jar;endorsed/xalan.jar;lib/tools.jar;lib/org.mortbay.jetty.jar;lib/org.apache.jasper.jar;lib/jspComm.jar;lib/mail.jar;lib/ao-util.jar;lib/gnu-regexp.jar;ccrt-client.jar;resources/com/bepco/rtc/properties;resources/com/bepco/rtc/oldproperties;lib/servlet.jar;lib/jfreechart-0.9.20.jar;lib/jcommon-0.9.5.jar;lib/jrgwin32-1_06.jar;lib/acrobat-libs.jar;lib/edtftpj-1.5.0.jar;lib/avalon-framework-4.2.0.jar;lib/batik-all-1.6.jar;lib/commons-io-1.1.jar;lib/commons-logging-1.0.4.jar;lib/fop-hyph.jar;lib/fop-sandbox.jar;lib/fop.jar;lib/xmlgraphics-commons-1.0.jar
COMMA=,
;=;
CHOSEN_INSTALL_BUNDLE_LIST=Applica,Help,JNI
\:=;
EXTRACTOR_DIR=O\:\\Software-EOL\\CCRT\\ClientBuilds\\BetaClientBuilds
EXECUTE_EXITCODE=4
USER_INSTALL_DIR=C\:\\Documents and Settings\\rsmith\\Desktop\\Tata.Oremco.Burke_PorterCCRT
IA_DEBUG=true
/=\\
SYSTEM=C\:\\WINDOWS\\system32
EXECUTE_STDOUT=\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>Echo ON \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>REM set env vars \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>for /F "tokens\=1-4 delims\=/ " %a in ('date /t') do (set weekday\=%a  & set month\=%b  & set day\=%c  & set year\=%d ) \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>(set weekday\=Fri  & set month\=05  & set day\=20  & set year\=2011 ) \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>REM Create the destination directory \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>set BACKUPDIR\=CCRT-20110520-BACKUP \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>Echo backup to CCRT-20110520-BACKUP \nbackup to CCRT-20110520-BACKUP\n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>REM Check if dir already exists \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>if exist \\CCRT-20110520-BACKUP goto CHECKDIR \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>GOTO COPYDIR \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>REM do the copy \n\nC\:\\Documents and Settings\\rsmith\\Local Settings\\Temp\\I1305898085\\Windows>xcopy /s /i C\:\\Documents and Settings\\rsmith\\Desktop\\Tata.Oremco.Burke_PorterCCRT \\CCRT-20110520-BACKUP \n
DESKTOP=C\:\\Documents and Settings\\rsmith\\Desktop
PARAM_1=C\:\\Documents and Settings\\rsmith\\Desktop\\Tata.Oremco.Burke_PorterCCRT
WIN_PROGRAMS_MENU=C\:\\Documents and Settings\\rsmith\\Start Menu\\Programs
CHOSEN_INSTALL_SET=Typical
NULL=
MACX_DOCK=
IA_CUSTOM_CODE_ZIP_SIZE=184415
PROGRAMS_DIR=C\:\\Program Files
WIN_COMMON_DESKTOP=C\:\\Documents and Settings\\All Users\\Desktop
EXECUTE_STDERR=Invalid number of parameters\n
CHOSEN_INSTALL_BUNDLE_3=JNI
SHORTCUT_NAME=Shortcut
CHOSEN_INSTALL_BUNDLE_2=Help
SYSTEM_DRIVE_ROOT=C\:\\
CHOSEN_INSTALL_BUNDLE_1=Applica
USER_HOME=C\:\\Documents and Settings\\rsmith
USER_SHORTCUTS=Do Not Install
DOLLAR=$
WIN_WINDOWS=C\:\\WINDOWS
WIN_QUICK_LAUNCH_BAR=C\:\\Documents and Settings\\rsmith\\Application Data\\Microsoft\\Internet Explorer\\Quick Launch\\
INSTALLER_TITLE=Burke Porter CCRT
MAC_EXTENSIONS=
UNIX_USER_HOME=C\:\\Documents and Settings\\rsmith
PRODUCT_VERSION_NUMBER=1.1.0.0
JAVA_HOME=C\:\\Documents and Settings\\rsmith\\Desktop\\Tata.Oremco.Burke_PorterCCRT\\jre
DO_NOT_INSTALL=Do Not Install
MACX_USER_APPLICATIONS=
CHOSEN_INSTALL_BUNDLE_NUM=3
FONTS=C\:\\WINDOWS\\Fonts
MAC_PREFERENCES=
IA_INSTALLER_STATUS=SUCCESS
UNIX_USR_LOCAL_BIN=
MAC_CHEWABLE=
