# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 10635 $

last_build_date=2011-05-13
core_build_today=2
cust_build_today=1
NAMETAG=Ccrt-C11051302
