panel.entervindialog.title=Enter Vehicle Barcode Number

main.icon=/com/bepco/rtc/images/CCRT_app_icon64.png

button.cancel.text=Close
button.enter.text=Enter VIN

barcode.vcnumber.startindex=0
barcode.vcnumber.length=12
barcode.vcnumber.datatag=VCNumber
barcode.vin.startindex=12
barcode.vin.length=17
barcode.vin.datatag=NextVIN
barcode.display.datatag=VINDisplay
barcode.error.insufficientlength=Barcode Number Not Long Enough!
