panel.entervindialog.title=Enter Vehicle Barcode Number
main.icon=/com/bepco/rtc/images/CCRT_app_icon64.png
button.cancel.text=Close
button.enter.text=Enter VIN
barcode.vcnumber.startindex=0
barcode.vcnumber.length=0
barcode.vcnumber.datatag=VCNumber
barcode.vin.startindex=0
barcode.vin.length=17
barcode.vin.datatag=NextVIN
barcode.display.datatag=VINDisplay
# barcode.error.insufficientlength=Input Data Not Long Enough!
barcode.error.insufficientlength = Barcode Number Not Long Enough!

