//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceReminder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaintenanceReminderLanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceReminderLanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaintenanceReminder.MaintenanceReminderLanguageResource", typeof(MaintenanceReminderLanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maintenance Note.
        /// </summary>
        internal static string AddMaintenanceNoteTitle {
            get {
                return ResourceManager.GetString("AddMaintenanceNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maintenance Reminder.
        /// </summary>
        internal static string AddMaintenanceReminderTitle {
            get {
                return ResourceManager.GetString("AddMaintenanceReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNoteLabel {
            get {
                return ResourceManager.GetString("AddNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reminder.
        /// </summary>
        internal static string AddReminderLabel {
            get {
                return ResourceManager.GetString("AddReminderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Field Is Blank.
        /// </summary>
        internal static string BlankFieldTitle {
            get {
                return ResourceManager.GetString("BlankFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Maintenance Item.
        /// </summary>
        internal static string CloseMaintenanceItemTitle {
            get {
                return ResourceManager.GetString("CloseMaintenanceItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ConfigureMenu {
            get {
                return ResourceManager.GetString("ConfigureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmAppExitMsg {
            get {
                return ResourceManager.GetString("ConfirmAppExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the Maintenance Tracker?.
        /// </summary>
        internal static string ConfirmAppExitTitle {
            get {
                return ResourceManager.GetString("ConfirmAppExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Following Reminders?.
        /// </summary>
        internal static string ConfirmDeleteMsg {
            get {
                return ResourceManager.GetString("ConfirmDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Reminder Delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current log File.
        /// </summary>
        internal static string CurrentLabel {
            get {
                return ResourceManager.GetString("CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reminder.
        /// </summary>
        internal static string DeleteReminderLabel {
            get {
                return ResourceManager.GetString("DeleteReminderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reminders.
        /// </summary>
        internal static string DeleteReminderTitle {
            get {
                return ResourceManager.GetString("DeleteReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Maintenance Reminder.
        /// </summary>
        internal static string EditMaintenanceReminderTitle {
            get {
                return ResourceManager.GetString("EditMaintenanceReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reminder.
        /// </summary>
        internal static string EditReminderLabel {
            get {
                return ResourceManager.GetString("EditReminderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        internal static string ElapsedTimeLabel {
            get {
                return ResourceManager.GetString("ElapsedTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishOption {
            get {
                return ResourceManager.GetString("EnglishOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer value..
        /// </summary>
        internal static string EnterIntegerMessage {
            get {
                return ResourceManager.GetString("EnterIntegerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a note in order to close this maintenance item..
        /// </summary>
        internal static string EnterMaintenanceNoteMsg {
            get {
                return ResourceManager.GetString("EnterMaintenanceNoteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your name in order to close this maintenance item..
        /// </summary>
        internal static string EnterNameMsg {
            get {
                return ResourceManager.GetString("EnterNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password:.
        /// </summary>
        internal static string EnterNewPasswordLabel {
            get {
                return ResourceManager.GetString("EnterNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        internal static string EnterNewPasswordTitle {
            get {
                return ResourceManager.GetString("EnterNewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the maintenance tracker program will prevent.
        /// </summary>
        internal static string ExitNotificationMsg1 {
            get {
                return ResourceManager.GetString("ExitNotificationMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance notifications from being displayed!.
        /// </summary>
        internal static string ExitNotificationMsg2 {
            get {
                return ResourceManager.GetString("ExitNotificationMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitOption {
            get {
                return ResourceManager.GetString("ExitOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Interval.
        /// </summary>
        internal static string IntervalLabel {
            get {
                return ResourceManager.GetString("IntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data Format.
        /// </summary>
        internal static string InvalidDataFormatTitle {
            get {
                return ResourceManager.GetString("InvalidDataFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address Format!.
        /// </summary>
        internal static string InvalidIpFormat {
            get {
                return ResourceManager.GetString("InvalidIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data supplied for Maintenance Interval..
        /// </summary>
        internal static string InvlaidIntervalMessage {
            get {
                return ResourceManager.GetString("InvlaidIntervalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Item field cannot be blank.
        /// </summary>
        internal static string ItemNotBlankMsg {
            get {
                return ResourceManager.GetString("ItemNotBlankMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Display Language.
        /// </summary>
        internal static string LocalizationTitle {
            get {
                return ResourceManager.GetString("LocalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files.
        /// </summary>
        internal static string LogFileLabel {
            get {
                return ResourceManager.GetString("LogFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Folder.
        /// </summary>
        internal static string LogFileLocationLabel {
            get {
                return ResourceManager.GetString("LogFileLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Complete.
        /// </summary>
        internal static string MaintenanceCompleteLabel {
            get {
                return ResourceManager.GetString("MaintenanceCompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Completed.
        /// </summary>
        internal static string MaintenanceCompleteLogMsg {
            get {
                return ResourceManager.GetString("MaintenanceCompleteLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Items.
        /// </summary>
        internal static string MaintenanceItemsLabel {
            get {
                return ResourceManager.GetString("MaintenanceItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to display when interval expires:.
        /// </summary>
        internal static string MaintenanceMessageLabel {
            get {
                return ResourceManager.GetString("MaintenanceMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay avisos seleccionados.
        /// </summary>
        internal static string MaintenanceNotCompleteLogMsg {
            get {
                return ResourceManager.GetString("MaintenanceNotCompleteLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Notes:.
        /// </summary>
        internal static string MaintenanceNotesLabel {
            get {
                return ResourceManager.GetString("MaintenanceNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Text.
        /// </summary>
        internal static string MaintenanceTextLabel {
            get {
                return ResourceManager.GetString("MaintenanceTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Maintenance Name.
        /// </summary>
        internal static string MissingNameTitle {
            get {
                return ResourceManager.GetString("MissingNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Maintenance Text.
        /// </summary>
        internal static string MissingTextTitle {
            get {
                return ResourceManager.GetString("MissingTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string NameRequiredMsg {
            get {
                return ResourceManager.GetString("NameRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        internal static string NameRequiredTitle {
            get {
                return ResourceManager.GetString("NameRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reminders selected..
        /// </summary>
        internal static string NoRemindersSelectedMsg {
            get {
                return ResourceManager.GetString("NoRemindersSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reminders Selected.
        /// </summary>
        internal static string NoRemindersSelectedTitle {
            get {
                return ResourceManager.GetString("NoRemindersSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not deleting any reminders..
        /// </summary>
        internal static string NotDeletingMsg {
            get {
                return ResourceManager.GetString("NotDeletingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesTitle {
            get {
                return ResourceManager.GetString("NotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Log Files.
        /// </summary>
        internal static string PreviousLabel {
            get {
                return ResourceManager.GetString("PreviousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QNX IP Address:.
        /// </summary>
        internal static string QnxIpAddressLabel {
            get {
                return ResourceManager.GetString("QnxIpAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QNX IP Address.
        /// </summary>
        internal static string QnxIpAddressMenuItem {
            get {
                return ResourceManager.GetString("QnxIpAddressMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new reminder:.
        /// </summary>
        internal static string ReminderAddedMsg {
            get {
                return ResourceManager.GetString("ReminderAddedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Reminder.
        /// </summary>
        internal static string ReminderAddedTitle {
            get {
                return ResourceManager.GetString("ReminderAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Configuration.
        /// </summary>
        internal static string ReminderConfigurationTitle {
            get {
                return ResourceManager.GetString("ReminderConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder already exists, not adding..
        /// </summary>
        internal static string ReminderExistsMessage {
            get {
                return ResourceManager.GetString("ReminderExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder already exists.
        /// </summary>
        internal static string ReminderExistsTitle {
            get {
                return ResourceManager.GetString("ReminderExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders:.
        /// </summary>
        internal static string ReminderListLabel {
            get {
                return ResourceManager.GetString("ReminderListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Item.
        /// </summary>
        internal static string ReminderNameLabel {
            get {
                return ResourceManager.GetString("ReminderNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Work Instruction Document.
        /// </summary>
        internal static string SelectWorkInstructionDocument {
            get {
                return ResourceManager.GetString("SelectWorkInstructionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string SpanishOption {
            get {
                return ResourceManager.GetString("SpanishOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string TimeRemainingLabel {
            get {
                return ResourceManager.GetString("TimeRemainingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated reminder item.
        /// </summary>
        internal static string UpdatedReminderMsg {
            get {
                return ResourceManager.GetString("UpdatedReminderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited reminder.
        /// </summary>
        internal static string UpdatedReminderTitle {
            get {
                return ResourceManager.GetString("UpdatedReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Notes.
        /// </summary>
        internal static string ViewNotesLabel {
            get {
                return ResourceManager.GetString("ViewNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Instruction Document:.
        /// </summary>
        internal static string WorkInstructionDocument {
            get {
                return ResourceManager.GetString("WorkInstructionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
