## filelist.properties
##
## This file is used to specify sources of playback data for 
## PlaybackServerDaemon.  

## The file to load realtime tracedata from (an actual tracelog file)
## (Normally, you won't need to change this value)
realtime.data = /local/playback/synthtracelog.dat


## Default values for certain tags are defined in this file.
## All datatypes automatically have a default value -- only
## tags that need custom default value need to be mentioned in
## this file.
## (Normally, you won't need to change this value)
## (A ".properties" extension is assumed for this value)
default.data = local.playback.defaultValues


## Asynchronous data value sources
## This type of source can consist of many files.  Eg, one file
## per test phase, or one file per tag, etc.
## To add files, iterate the third field in the names below, eg,
## the 15th file you add would have the id "test.data.15"
## --> The ordering and organization of the files DOES NOT MATTER. 
## All events dictated in the files will be compiled into one complete
## event list, organized by time.
##
test.data.1 = /local/playback/testsequence.dat
test.data.2 = /local/playback/tpsvalues.dat
test.data.3 = /local/playback/powersupply.dat
test.data.4 = /local/playback/prompts.dat

## Eg, test.data.N  = phaseN.dat
