# Localization for testresultviewer
panel.testresultviewer.title=Server Test Result Viewer
panel.intro.screen=/com/bepco/rtc/images/CCRT_splash.png

main.icon=/com/bepco/rtc/images/CCRT_app_icon64.png

command.resendresult.hostservername=core/PlantHostOutbound
command.resendresult.testresultpath=/TestResults/Vehicle/
command.resendResult.QNXUserName=CCRT
command.savereport.defaultOpenPath=C:\\
command.savereport.defaultSavePath=C:\\
# ----------------------------------------------------------------------
# Strings for display on the GUI Components for the TestResultView Panel
# ----------------------------------------------------------------------
label.testresult.text=Test Result
label.newresult.text=New Test Result Available
button.load.text=Open
button.tooltip.load.text=Open a vehicle test result from the server
button.loadlatest.text=Load Latest Result
button.tooltip.loadlatest.text=Load the latest test result from the server
button.printreport.text=Print Report
button.tooltip.printreport.text=Print Entire Test Report to Report Printer
button.printtab.text=Print Tab
button.tooltip.printtab.text=Print the current tab view
button.resendresults.text=Resend Result
button.tooltip.resendresults.text=Resend the result to the plant host system
button.savereports.text=Save Report
button.tooltip.savereports.text=Save Electronic Copy Of the Test Report
message.error.invaliddocument.text=Invalid Test Result Document
message.error.noresultloaded.text=No test result loaded
message.error.notabselected.text=No tab selected to print
tabreport.filename.text=File Name
tabreport.testname.text=Test Name

# ----------------------------------------------------------------------
# Strings for display on the GUI Components for the File Load Dialog Box
# ----------------------------------------------------------------------
dialog.title.fileview.text=Load Test Result File
table.column.0.text=VIN Number
table.column.1.text=Date and Time
label.findvin.text=Enter last 6 of VIN
button.ok.text=OK
button.tooltip.ok.text=Load Test Result for Selected VIN
button.cancel.text=Cancel
button.tooltip.cancel.text=Exit with out loading a Test Result
button.findnext.text=Find Next
button.tooltip.findnext.text=Search Table for the next VIN whose ending characters match the ones in the field above
button.browse.text=Browse...
button.tooltip.browse.text=Open file browser to load test result from
message.info.enteraddress.text=Please Enter Ip Address for Server or localhost
message.error.connecterror.text=Unable to connect to host, using localhost
message.error.invalidselection.text=Invalid selection
message.info.noselection.text=Please select a test result from the list
message.info.novinfound.text=VIN not found
timezone=EST
