# The full path to the layout XML file to use
#layoutfile=C:\\Burke_PorterCCRT\\resources\\local\\report\\reportlayoutExample.xml
layoutfile=/home/john/cvswork/bepco/src/local/report/NewReportLayout.xml
testresultsfile=/home/john/cvswork/bepco/src/local/ftproot/home/ftp/TestResults/Vehicle/realresults.xml

# The units conversion to use, either 'Metric' or 'English' (without quotes)
unitsystem=English

# Names of the browsers for different platforms
linuxbrowser=mozilla
windowsbrowser=c:\\Program Files\\Internet Explorer\\iexplore.exe
