# Localization for logviewer 

panel.clientlogviewer.title=Client Log Viewer

filechooser.logviewer.dialogtitle = Save a Log File

filechooser.save.overwrite.title = File Already Exists
filechooser.save.overwrite = Confirm Overwrite
filechooser.save.error = Cannot save file
