# Properties for the LIcense backup/restore utility
frame.title=License Backup utility
action.close.name=Close
action.close.description=Close this window
action.backup.name=Backup
action.backup.description=Backup the selected license files to a local directory
backup.directory=C:\\CCRT Backup\\Licenses

