#User Preferences for Burke Porter CCRT
#Thu Jun 20 16:23:37 GMT 2013
controlline.licensefatal.model=InvalidLicenseFatalFault
preference.logging=CONFIG
settings.ticketprinter.printonpass=true
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.AshokLeyland.ReportLayout.Reg.xsl
controlline.starttest.model=StartTest
controlline.licensewarning.model=InvalidLicenseNotification
preference.units=Metric
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
network.useproxy=false
network.ftppassword=porter
server.address.failsafe=172.16.250.3
settings.reportprinter.name=TEC B-452
settings.ticketprinter.printonfail=true
controlline.rackmonitor.model=DisplayRackMonitor
settings.printer.localize=true
controlline.drivermonitor.model=DisplayDriverMonitor
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.AshokLeyland.ReportLayout.Reg.xsl
server.address=192.168.1.1
preference.country.iso=US
email.smtp.host=localhost
network.ftproot=/home/ftp
settings.ticketprinter.name.right=TEC B-452
preference.language.iso=en
email.from=CCRT System <ccrt@bepco.com>
network.ftpuser=burke
settings.reportprinter.printonpass=false
settings.reportprinter.name.right=TEC B-452
controlline.testinprogress.model=TestInProgress
server.use.stored.address=true
settings.graphicsprinter.enabled=false
settings.clicktoexit.value=false
controlline.testresults.model=TestResultToPrint
controlline.softwareid.model=SoftwareID
settings.reportprinter.printonfail=false
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
settings.ticketprinter.name=TEC B-452
