#User Preferences for Burke Porter CCRT
#Wed Nov 30 09:09:51 GMT 2011
controlline.licensefatal.model=InvalidLicenseFatalFault
preference.logging=CONFIG
settings.ticketprinter.printonpass=false
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Chinese.TicketReportLayout.xsl
controlline.starttest.model=StartTest
controlline.licensewarning.model=InvalidLicenseNotification
preference.units=Metric
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ChanganReportLayout.xml
network.useproxy=false
network.ftppassword=porter
server.address.failsafe=172.16.253.101
settings.reportprinter.name=EPSON TM-U220D Receipt
settings.ticketprinter.printonfail=false
controlline.rackmonitor.model=DisplayRackMonitor
settings.printer.localize=true
controlline.drivermonitor.model=DisplayDriverMonitor
preference.units.useNForceUnits=true
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Chinese.TicketReportLayout.xsl
server.address=192.168.1.1
preference.country.iso=CN
email.smtp.host=localhost
network.ftproot=/home/ftp
preference.language.iso=zh
email.from=CCRT System <ccrt@bepco.com>
network.ftpuser=burke
settings.reportprinter.printonpass=true
settings.reportprinter.name.right=HP Officejet Pro K5400 Series
controlline.testinprogress.model=TestInProgress
server.use.stored.address=true
settings.graphicsprinter.enabled=false
settings.clicktoexit.value=false
controlline.testresults.model=TestResultToPrint
settings.ticketprinter.name=EPSON TM-U220D Receipt
settings.reportprinter.printonfail=true
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\ChanganReportLayout.xml
controlline.softwareid.model=SoftwareID
