#User Preferences for Burke Porter CCRT
#Sat Nov 19 03:05:22 GMT 2011
controlline.licensefatal.model=InvalidLicenseFatalFault
preference.logging=CONFIG
settings.ticketprinter.printonpass=false
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.Oremco.ReportLayout.Reg.xsl
preference.logrotation.numberoflogfiles=10
controlline.starttest.model=StartTest
controlline.licensewarning.model=InvalidLicenseNotification
preference.units=Metric
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.ReportLayout.xml
network.useproxy=false
network.ftppassword=porter
server.address.failsafe=192.168.1.1
settings.reportprinter.name=LH EPSON TM-U220 Receipt
settings.ticketprinter.printonfail=false
controlline.rackmonitor.model=DisplayRackMonitor
settings.printer.localize=true
controlline.drivermonitor.model=DisplayDriverMonitor
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.Oremco.ReportLayout.Reg.xsl
server.address=192.168.1.1
preference.country.iso=US
email.smtp.host=localhost
network.ftproot=/home/ftp
settings.ticketprinter.name.right=RH PRINTER
preference.language.iso=en
email.from=CCRT System <ccrt@bepco.com>
network.ftpuser=burke
settings.reportprinter.printonpass=true
preference.logrotation.logfilesizekilobytes=3000
settings.reportprinter.name.right=RH EPSON TM-U220 Receipt
controlline.testinprogress.model=TestInProgress
preference.logrotation.logfilepath=C\:\\Burke_PorterCCRT\\resources\\local\\logs
server.use.stored.address=true
settings.graphicsprinter.enabled=false
settings.clicktoexit.value=false
controlline.testresults.model=TestResultToPrint
settings.ticketprinter.name=LH PRINTER
settings.reportprinter.printonfail=true
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.ReportLayout.xml
controlline.softwareid.model=SoftwareID
