# Keys for the Network config panel
#
network.serverselection.label=CCRT Server Config
network.host.label=Server Address
network.host.tip=Enter IP address or hostname of the Real Time Server
network.host.error.message=Unknown host address {0}.
network.host.error.title=Host address error
network.emailpanel.label=Email Config
network.email.error.message=Bad Email addres entered.
network.email.error.title=Email From Address Error
network.smtphost.label=SMTP Server
network.smtphost.tip=Enter IP address or hostname of the outgoing mail server
network.smtphost.error.message=Bad SMTP server address entered.
network.smtphost.error.title=SMTP Address Error
network.mailfrom.label=Email From
network.mailfrom.tip=Enter the address that will appear in the "from" field of outgoing email
network.mailfrom.error.message=Invalid "from" address entered.
network.mailfrom.error.title=Mail "from" Error
network.usestored.label=Use at startup?
network.usestored.tip=Always use this server address at application start up

network.port.label=Server Port
network.port.tip=Enter port number of the Real Time Server

network.ftppanel.label=FTP Config
network.ftpuser.label=FTP User
network.ftppassword.label=FTP Password
network.ftproot.label=FTP Root
network.ftpuser.tip=Enter the user name for FTP access on the server
network.ftppassword.tip=Enter the password for the FTP user on the server
network.ftproot.tip=Enter the root directory for data available via FTP on the server
