//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomFileProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BomFileProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bep_best {
            get {
                object obj = ResourceManager.GetObject("bep_best", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Code.
        /// </summary>
        internal static string BomBookCodeColumnName {
            get {
                return ResourceManager.GetString("BomBookCodeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD.
        /// </summary>
        internal static string BomDetailLineIndicator {
            get {
                return ResourceManager.GetString("BomDetailLineIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNA.
        /// </summary>
        internal static string BomFnaColumnText {
            get {
                return ResourceManager.GetString("BomFnaColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number.
        /// </summary>
        internal static string BomLotNumberColumnName {
            get {
                return ResourceManager.GetString("BomLotNumberColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Code.
        /// </summary>
        internal static string BomModelCodeColumnName {
            get {
                return ResourceManager.GetString("BomModelCodeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        internal static string BomModelYearColumnName {
            get {
                return ResourceManager.GetString("BomModelYearColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        internal static string BomPartNameColumnText {
            get {
                return ResourceManager.GetString("BomPartNameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string BomPartNumberColumnText {
            get {
                return ResourceManager.GetString("BomPartNumberColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM Record Count.
        /// </summary>
        internal static string BomRecordCountColumnText {
            get {
                return ResourceManager.GetString("BomRecordCountColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BOM Count.
        /// </summary>
        internal static string BomTotalBomCountColumnText {
            get {
                return ResourceManager.GetString("BomTotalBomCountColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC.
        /// </summary>
        internal static string BomUpcColumnText {
            get {
                return ResourceManager.GetString("BomUpcColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildItemList.xml.
        /// </summary>
        internal static string BuidlItemFileName {
            get {
                return ResourceManager.GetString("BuidlItemFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Temp\Archive\.
        /// </summary>
        internal static string DefaultBomArchive {
            get {
                return ResourceManager.GetString("DefaultBomArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Temp\.
        /// </summary>
        internal static string DefaultBomDirectory {
            get {
                return ResourceManager.GetString("DefaultBomDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Temp\Result\.
        /// </summary>
        internal static string DefaultBomResultDirectory {
            get {
                return ResourceManager.GetString("DefaultBomResultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Temp\.
        /// </summary>
        internal static string DefaultVehicleBuildFolder {
            get {
                return ResourceManager.GetString("DefaultVehicleBuildFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BomFileProcessor.
        /// </summary>
        internal static string LogFileBase {
            get {
                return ResourceManager.GetString("LogFileBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string LogFileExtension {
            get {
                return ResourceManager.GetString("LogFileExtension", resourceCulture);
            }
        }
    }
}
