//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomFileProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BOM\\BOM")]
        public string BomDirectory {
            get {
                return ((string)(this["BomDirectory"]));
            }
            set {
                this["BomDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BOM\\Archive")]
        public string BomArchive {
            get {
                return ((string)(this["BomArchive"]));
            }
            set {
                this["BomArchive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BOM\\Results")]
        public string BomResultDirectory {
            get {
                return ((string)(this["BomResultDirectory"]));
            }
            set {
                this["BomResultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Rewrite\\Configuration\\VehicleTest\\BuildRecords")]
        public string VehicleBuildDirectory {
            get {
                return ((string)(this["VehicleBuildDirectory"]));
            }
            set {
                this["VehicleBuildDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public int BomUpcIndex {
            get {
                return ((int)(this["BomUpcIndex"]));
            }
            set {
                this["BomUpcIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BomUpcLength {
            get {
                return ((int)(this["BomUpcLength"]));
            }
            set {
                this["BomUpcLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int BomFnaIndex {
            get {
                return ((int)(this["BomFnaIndex"]));
            }
            set {
                this["BomFnaIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BomFnaLength {
            get {
                return ((int)(this["BomFnaLength"]));
            }
            set {
                this["BomFnaLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int BomPartNumberIndex {
            get {
                return ((int)(this["BomPartNumberIndex"]));
            }
            set {
                this["BomPartNumberIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BomPartNumberLength {
            get {
                return ((int)(this["BomPartNumberLength"]));
            }
            set {
                this["BomPartNumberLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BomPartNameIndex {
            get {
                return ((int)(this["BomPartNameIndex"]));
            }
            set {
                this["BomPartNameIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BomPartNameLength {
            get {
                return ((int)(this["BomPartNameLength"]));
            }
            set {
                this["BomPartNameLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int BomCountIndex {
            get {
                return ((int)(this["BomCountIndex"]));
            }
            set {
                this["BomCountIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int BomCountLength {
            get {
                return ((int)(this["BomCountLength"]));
            }
            set {
                this["BomCountLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BomRecordCountIndex {
            get {
                return ((int)(this["BomRecordCountIndex"]));
            }
            set {
                this["BomRecordCountIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BomRecordCountLength {
            get {
                return ((int)(this["BomRecordCountLength"]));
            }
            set {
                this["BomRecordCountLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int BomModelCodeIndex {
            get {
                return ((int)(this["BomModelCodeIndex"]));
            }
            set {
                this["BomModelCodeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BomModelCodeLength {
            get {
                return ((int)(this["BomModelCodeLength"]));
            }
            set {
                this["BomModelCodeLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BomModelYearIndex {
            get {
                return ((int)(this["BomModelYearIndex"]));
            }
            set {
                this["BomModelYearIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BomModelYearLength {
            get {
                return ((int)(this["BomModelYearLength"]));
            }
            set {
                this["BomModelYearLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BomLotNumberIndex {
            get {
                return ((int)(this["BomLotNumberIndex"]));
            }
            set {
                this["BomLotNumberIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BomLotNumberLength {
            get {
                return ((int)(this["BomLotNumberLength"]));
            }
            set {
                this["BomLotNumberLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public int BomBookCodeIndex {
            get {
                return ((int)(this["BomBookCodeIndex"]));
            }
            set {
                this["BomBookCodeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int BomBookCodeLength {
            get {
                return ((int)(this["BomBookCodeLength"]));
            }
            set {
                this["BomBookCodeLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BOM\\DVT")]
        public string SpartanFileLocation {
            get {
                return ((string)(this["SpartanFileLocation"]));
            }
            set {
                this["SpartanFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Rewrite\\TestResults\\PassConfirmation")]
        public string CcrtFileLocation {
            get {
                return ((string)(this["CcrtFileLocation"]));
            }
            set {
                this["CcrtFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForPassConfirmationFiles {
            get {
                return ((bool)(this["CheckForPassConfirmationFiles"]));
            }
            set {
                this["CheckForPassConfirmationFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int PassConfirmationCheckDelay {
            get {
                return ((int)(this["PassConfirmationCheckDelay"]));
            }
            set {
                this["PassConfirmationCheckDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BOM\\ECM")]
        public string SpartanFlashFileLocation {
            get {
                return ((string)(this["SpartanFlashFileLocation"]));
            }
            set {
                this["SpartanFlashFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BOM\\ESN")]
        public string WindowsPCESNFileLocation {
            get {
                return ((string)(this["WindowsPCESNFileLocation"]));
            }
            set {
                this["WindowsPCESNFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Rewrite\\TestResults\\ESN")]
        public string RealTimePCESNFileLocation {
            get {
                return ((string)(this["RealTimePCESNFileLocation"]));
            }
            set {
                this["RealTimePCESNFileLocation"] = value;
            }
        }
    }
}
