#User Preferences for Burke Porter CCRT
#Fri Jul 20 12:12:14 GMT 2012
server.address.failsafe=172.16.250.3
controlline.drivermonitor.model=DisplayDriverMonitor
settings.clicktoexit.value=false
server.address=192.168.1.1
controlline.starttest.model=StartTest
settings.reportprinter.name=EPSON TM-U220 Receipt
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=US
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=C\:\\Ccrt\\Ccrt\\branches\\Common3700\\Source\\Mahindra\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
preference.language.iso=en
controlline.testresults.model=TestResultToPrint
settings.reportprinter.layout=C\:\\Ccrt\\Ccrt\\branches\\Common3700\\Source\\Mahindra\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
settings.printer.localize=true
settings.ticketprinter.printonpass=false
preference.units=Metric
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
settings.graphicsprinter.enabled=false
controlline.licensewarning.model=InvalidLicenseNotification
settings.reportprinter.printonpass=false
network.ftppassword=porter
network.useproxy=false
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
settings.reportprinter.xslt=C\:\\Ccrt\\Ccrt\\branches\\Common3700\\Source\\Mahindra\\Burke_PorterCCRT\\resources\\local\\report\\Tata.AshokLeyland.ReportLayout.Reg.xsl
server.use.stored.address=true
settings.ticketprinter.xslt=C\:\\Ccrt\\Ccrt\\branches\\Common3700\\Source\\Mahindra\\Burke_PorterCCRT\\resources\\local\\report\\Tata.AshokLeyland.ReportLayout.Reg.xsl
settings.reportprinter.printonfail=false
