#User Preferences for Burke Porter CCRT
#Fri Jun 21 19:48:33 GMT 2013
server.address.failsafe=192.168.1.1
controlline.drivermonitor.model=DisplayDriverMonitor
settings.clicktoexit.value=false
server.address=192.168.1.1
controlline.starttest.model=StartTest
settings.reportprinter.name=EPSON LX-300+ /II
network.ftpuser=burke
email.from=CCRT System <ccrt@bepco.com>
controlline.softwareid.model=SoftwareID
preference.country.iso=US
controlline.testinprogress.model=TestInProgress
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
preference.language.iso=en
preference.units.useNForceUnits=true
controlline.testresults.model=TestResultToPrint
settings.reportprinter.name.right=EPSON LX-300+ /II
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
settings.printer.localize=true
settings.ticketprinter.printonpass=false
preference.units=Metric
preference.logging=CONFIG
controlline.licensefatal.model=InvalidLicenseFatalFault
controlline.licensewarning.model=InvalidLicenseNotification
settings.graphicsprinter.enabled=false
settings.reportprinter.printonpass=false
network.useproxy=true
network.ftppassword=porter
controlline.rackmonitor.model=DisplayRackMonitor
settings.ticketprinter.printonfail=false
email.smtp.host=localhost
network.ftproot=/home/ftp
server.use.stored.address=true
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\MahindraReportLayout.xsl
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\MahindraReportLayout.xsl
settings.reportprinter.printonfail=true
