#User Preferences for Burke Porter CCRT
#Fri Aug 10 01:07:13 GMT 2012
controlline.drivermonitor.model=DisplayDriverMonitor
controlline.licensefatal.model=InvalidLicenseFatalFault
controlline.licensewarning.model=InvalidLicenseNotification
controlline.rackmonitor.model=DisplayRackMonitor
controlline.softwareid.model=SoftwareID
controlline.starttest.model=StartTest
controlline.testinprogress.model=TestInProgress
controlline.testresults.model=TestResultToPrint
email.from=CCRT System <ccrt@bepco.com>
email.smtp.host=localhost
network.ftppassword=porter
network.ftproot=/home/ftp
network.ftpuser=burke
network.useproxy=false
preference.country.iso=US
preference.language.iso=en
preference.logging=CONFIG
preference.units=Metric
server.address.failsafe=172.16.250.3
server.address=192.168.1.1
server.use.stored.address=true
settings.clicktoexit.value=false
settings.graphicsprinter.enabled=false
settings.printer.localize=true
settings.reportprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
settings.reportprinter.name.right=TEC B-452
settings.reportprinter.name=TEC B-452
settings.reportprinter.printonfail=false
settings.reportprinter.printonpass=false
settings.reportprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.AshokLeyland.ReportLayout.Reg.xsl
settings.ticketprinter.layout=C\:\\Burke_PorterCCRT\\resources\\local\\report\\NewReportLayout.xml
settings.ticketprinter.name.right=TEC B-452
settings.ticketprinter.name=TEC B-452
settings.ticketprinter.printonfail=true
settings.ticketprinter.printonpass=true
settings.ticketprinter.xslt=C\:\\Burke_PorterCCRT\\resources\\local\\report\\Tata.AshokLeyland.ReportLayout.Reg.xsl
