# build today properties
# This file must be parseable by Bourne Shell
# No spaces are allowed in the properties!
# $Revision: 9497 $

last_build_date=2007-03-06
core_build_today=2
cust_build_today=1
NAMETAG=Ccrt-C07030602
