# Keys for report config panel
#
report.validate.button=Validate
report.validate.success=File Validated Successfully
report.validate.invalid.title=Invalid Format
report.report.layout.validate.invalid.message=<html><font color=\"red\">Report Layout will be currupt.</font></html>
report.report.xslt.validate.invalid.message=<html><font color=\"red\">Report Transform will be currupt.</font></html>
report.ticket.layout.validate.invalid.message=<html><font color=\"red\">Ticket Layout will be currupt.</font></html>
report.ticket.xslt.validate.invalid.message=<html><font color=\"red\">Ticket Transform will be currupt.</font></html>
report.filefilter.description=Printer Layout Files (*.xml)
report.report.layout.label=Report Printer Layout
report.report.layout.field.tip=Currently used report printer layout
report.report.layout.browse.label=Browse
report.report.layout.browse.tip=Change current report printer layout
report.ticket.layout.label=Ticket Printer Layout
report.ticket.layout.field.tip=Currently used ticket printer layout
report.ticket.layout.browse.label=Browse
report.ticket.layout.browse.tip=Change current ticket printer layout
report.layout.label=Printer Layout Configuration
report.config.label=Printer Configuration
report.report.layout.tabbedpane.label=Report Printer Layout
report.report.xslt.tabbedpane.label=Report Printer XSLT
report.ticket.layout.tabbedpane.label=Ticket Printer Layout
report.ticket.xslt.tabbedpane.label=Ticket Printer XSLT
# Printer XSLT Configuration
transform.filefilter.description=Printer Transform Files (*.xsl)
transform.report.browse.label=Browse
transform.report.browse.tip=Change current report printer transformation
transform.report.field.tip=Currently used report printer transformation
transform.report.label=Report Printer XSLT
transform.report.validate.invalid.message=<html><font color=\"red\">Report Transform will be currupt.</font></html>
transform.ticket.browse.label=Browse
transform.ticket.browse.tip=Change current ticket printer transformation
transform.ticket.field.tip=Currently used ticket printer transformation
transform.ticket.label=Ticket Printer XSLT
transform.ticket.validate.invalid.message=<html><font color=\"red\">Ticket Transform will be currupt.</font></html>
report.report.validate.invalid.message=<html><font color=\"red\">Report Configuration will be currupt.</font></html>
report.ticket.validate.invalid.message=<html><font color=\"red\">Ticket Configuration will be currupt.</font></html>
report.report.tabbedpane.label=Report Printer Layout
report.ticket.tabbedpane.label=Ticket Printer Layout

